using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace indice.Edi.Tests.Issue256.Qualifiers;

/// <summary>
/// Code list responsible agency, coded
/// </summary>
public class CodeListResponsibleAgencyCoded
{
	/// <summary>
	/// String assign converter
	/// </summary>
	public static implicit operator CodeListResponsibleAgencyCoded(string s) => new CodeListResponsibleAgencyCoded { Code = s };

	/// <summary>
	/// Code of the value
	/// </summary>
	public string? Code { get; set; }

	/// <summary>
	/// Value converted from code
	/// </summary>
	public string? Value => Code is null ? null : (Qualifiers.ContainsKey(Code) ? Qualifiers[Code] : null);

	/// <summary>
	/// All possible values
	/// </summary>
	[JsonIgnore]
	public Dictionary<string, string> Qualifiers => new Dictionary<string, string>
	{
		{ "1", "CCC (Customs Co-operation Council)" },
		{ "2", "CEC (Commission of the European Communities)" },
		{ "3", "IATA (International Air Transport Association)" },
		{ "4", "ICC (International Chamber of Commerce)" },
		{ "5", "ISO (International Organization for Standardization)" },
		{ "6", "UN/ECE (United Nations - Economic Commission for Europe)" },
		{ "7", "CEFIC (Conseil Europeen des Federations de l'Industrie Chimique)" },
		{ "8", "EDIFICE" },
		{ "9", "EAN (International Article Numbering association)" },
		{ "10", "ODETTE" },
		{ "11", "Lloyd's register of shipping" },
		{ "12", "UIC (International union of railways)" },
		{ "13", "ICAO (International Civil Aviation Organisation)" },
		{ "14", "ICS (International Chamber of Shipping)" },
		{ "15", "RINET (Reinsurance and Insurance Network)" },
		{ "16", "DUNS (Dun & Bradstreet)" },
		{ "17", "S.W.I.F.T." },
		{ "18", "Conventions on SAD and transit (EC and EFTA)" },
		{ "19", "FRRC (Federal Reserve Routing Code)" },
		{ "20", "BIC (Bureau International des Containeurs)" },
		{ "21", "Assigned by transport company" },
		{ "22", "US, ISA (Information Systems Agreement)" },
		{ "23", "FR, EDITRANSPORT" },
		{ "24", "AU, ROA (Railways of Australia)" },
		{ "25", "EDITEX (Europe)" },
		{ "26", "NL, Foundation Uniform Transport Code" },
		{ "27", "US, FDA (Food and Drug Administration)" },
		{ "28", "EDITEUR (European book sector electronic data interchange group)" },
		{ "29", "GB, FLEETNET" },
		{ "30", "GB, ABTA (Association of British Travel Agencies)" },
		{ "31", "FI, Finish State Railway" },
		{ "32", "PL, Polish State Railway" },
		{ "33", "BG, Bulgaria State Railway" },
		{ "34", "RO, Rumanian State Railway" },
		{ "35", "CZ, Tchechian State Railway" },
		{ "36", "HU, Hungarian State Railway" },
		{ "37", "GB, British Railways" },
		{ "38", "ES, Spanish National Railway" },
		{ "39", "SE, Swedish State Railway" },
		{ "40", "NO, Norwegian State Railway" },
		{ "41", "DE, German Railway" },
		{ "42", "AT, Austrian Federal Railways" },
		{ "43", "LU, Luxembourg National Railway Company" },
		{ "44", "IT, Italian State Railways" },
		{ "45", "NL, Netherlands Railways" },
		{ "46", "CH, Swiss Federal Railways" },
		{ "47", "DK, Danish State Railways" },
		{ "48", "FR, French National Railway Company" },
		{ "49", "BE, Belgian National Railway Company" },
		{ "50", "PT, Portuguese Railways" },
		{ "51", "SK, Slovakian State Railways" },
		{ "52", "IE, Irish Transport Company" },
		{ "53", "FIATA (International Federation of Freight Forwarders Associations)" },
		{ "54", "IMO (International Maritime Organisation)" },
		{ "55", "US, DOT (United States Department of Transportation)" },
		{ "56", "TW, Trade-van" },
		{ "57", "TW, Chinese Taipei Customs" },
		{ "58", "EUROFER" },
		{ "59", "DE, EDIBAU" },
		{ "60", "Assigned by national trade agency" },
		{ "61", "Association Europeenne des Constructeurs de Materiel Aerospatial (AECMA)" },
		{ "62", "US, DIstilled Spirits Council of the United States (DISCUS)" },
		{ "63", "North Atlantic Treaty Organization (NATO)" },
		{ "64", "FR, EDIFRANCE" },
		{ "65", "FR, GENCOD" },
		{ "66", "MY, Malaysian Customs and Excise" },
		{ "67", "MY, Malaysia Central Bank" },
		{ "68", "US, Bureau of Alcohol, Tobacco and Firearms (BATF)" },
		{ "69", "US, National Alcohol Beverage Control Association (NABCA)" },
		{ "70", "MY, Dagang.Net" },
		{ "71", "US, FCC (Federal Communications Commission)" },
		{ "72", "US, MARAD (Maritime Administration)" },
		{ "73", "US, DSAA (Defense Security Assistance Agency)" },
		{ "74", "US, NRC (Nuclear Regulatory Commission)" },
		{ "75", "US, ODTC (Office of Defense Trade Controls)" },
		{ "76", "US, ATF (Bureau of Alcohol, Tobacco and Firearms)" },
		{ "77", "US, BXA (Bureau of Export Administration)" },
		{ "78", "US, FWS (Fish and Wildlife Service)" },
		{ "79", "US, OFAC (Office of Foreign Assets Control)" },
		{ "80", "BRMA/RAA - LIMNET - RINET Joint Venture" },
		{ "81", "RU, (SFT) Society for Financial Telecommunications" },
		{ "82", "NO, Enhetsregisteret ved Bronnoysundregisterne" },
		{ "83", "US, National Retail Federation" },
		{ "84", "DE, BRD (Gesetzgeber der Bundesrepublik Deutschland)" },
		{ "85", "North America, Telecommunications Industry Forum" },
		{ "86", "Assigned by party originating the message" },
		{ "87", "Assigned by carrier" },
		{ "88", "Assigned by owner of operation" },
		{ "89", "Assigned by distributor" },
		{ "90", "Assigned by manufacturer" },
		{ "91", "Assigned by seller or seller's agent" },
		{ "92", "Assigned by buyer or buyer's agent" },
		{ "93", "AT, Austrian Customs" },
		{ "94", "AT, Austrian PTT" },
		{ "95", "AU, Australian Customs Services" },
		{ "96", "CA, Revenue Canada, Customs and Excise" },
		{ "97", "CH, Administration federale des contributions" },
		{ "98", "CH, Direction generale des douanes" },
		{ "99", "CH, Division des importations et exportations, OFAEE" },
		{ "100", "CH, Entreprise des PTT" },
		{ "101", "CH, Carbura" },
		{ "102", "CH, Centrale suisse pour l'importation du charbon" },
		{ "103", "CH, Office fiduciaire des importateurs de denrees alimentaires" },
		{ "104", "CH, Association suisse code des articles" },
		{ "105", "DK, Ministry of taxation, Central Customs and Tax Administration" },
		{ "106", "FR, Direction generale des douanes et droits indirects" },
		{ "107", "FR, INSEE" },
		{ "108", "FR, Banque de France" },
		{ "109", "GB, H.M. Customs & Excise" },
		{ "110", "IE, Revenue Commissionners, Customs AEP project" },
		{ "111", "US, U.S. Customs Service" },
		{ "112", "US, U.S. Census Bureau" },
		{ "113", "US, UCC (Uniform Code Council)" },
		{ "114", "US, ABA (American Bankers Association)" },
		{ "115", "US, DODAAC (Department Of Defense Active Agency Code)" },
		{ "116", "US, ANSI ASC X12" },
		{ "117", "AT, Geldausgabeautomaten-Service Gesellschaft m.b.H." },
		{ "118", "SE, Svenska Bankfoereningen" },
		{ "119", "IT, Associazione Bancaria Italiana" },
		{ "120", "IT, Socieata' Interbancaria per l'Automazione" },
		{ "121", "CH, Telekurs AG" },
		{ "122", "CH, Swiss Securities Clearing Corporation" },
		{ "123", "NO, Norwegian Interbank Research Organization" },
		{ "124", "NO, Norwegian Bankers Ass." },
		{ "125", "FI, The Finnish Bankers' Association" },
		{ "126", "US, NCCMA (Account Analysis Codes)" },
		{ "128", "BE, Belgian Bankers' Association" },
		{ "129", "BE, Belgian Ministry of Finance" },
		{ "130", "DK, PBS (Pengainstitutternes Betalings Service)" },
		{ "131", "DE, German Bankers Association" },
		{ "132", "GB, BACS Limited" },
		{ "133", "GB, Association for Payment Clearing Services" },
		{ "134", "GB, CHAPS and Town Clearing Company Ltd." },
		{ "135", "GB, The Clearing House" },
		{ "136", "GB, Article Number Association (UK) Limited" },
		{ "137", "AT, Verband oesterreichischer Banken und Bankiers" },
		{ "138", "FR, CFONB (Comite francais d'organ. et de normalisation bancaires)" },
		{ "139", "UPU (Universal Postal Union)" },
		{ "140", "CEC (Commission of the European Communities), DG/XXI-01" },
		{ "141", "CEC (Commission of the European Communities), DG/XXI-B-1" },
		{ "142", "CEC (Commission of the European Communities), DG/XXXIV" },
		{ "143", "NZ, New Zealand Customs" },
		{ "144", "NL, Netherlands Customs" },
		{ "145", "SE, Swedish Customs" },
		{ "146", "DE, German Customs" },
		{ "147", "BE, Belgian Customs" },
		{ "148", "ES, Spanish Customs" },
		{ "149", "IL, Israel Customs" },
		{ "150", "HK, Hong Kong Customs" },
		{ "151", "JP, Japan Customs" },
		{ "152", "SA, Saudi Arabia Customs" },
		{ "153", "IT, Italian Customs" },
		{ "154", "GR, Greek Customs" },
		{ "155", "PT, Portuguese Customs" },
		{ "156", "LU, Luxembourg Customs" },
		{ "157", "NO, Norwegian Customs" },
		{ "158", "FI, Finnish Customs" },
		{ "159", "IS, Iceland Customs" },
		{ "160", "LI, Liechtenstein authority" },
		{ "161", "UNCTAD (United Nations - Conference on Trade And Development)" },
		{ "162", "CEC (Commission of the European Communities), DG/XIII-D-5" },
		{ "163", "US, FMC (Federal Maritime Commission)" },
		{ "164", "US, DEA (Drug Enforcement Agency)" },
		{ "165", "US, DCI (Distribution Codes, INC.)" },
		{ "166", "US, National Motor Freight Classification Association" },
		{ "167", "US, AIAG (Automotive Industry Action Group)" },
		{ "168", "US, FIPS (Federal Information Publishing Standard)" },
		{ "169", "CA, SCC (Standards Council of Canada)" },
		{ "170", "CA, CPA (Canadian Payment Association)" },
		{ "171", "NL, Bank Girocentrale BV" },
		{ "172", "NL, BEANET BV" },
		{ "173", "NO, NORPRO" },
		{ "174", "DE, DIN (Deutsches Institut fuer Normung)" },
		{ "175", "FCI (Factors Chain International)" },
		{ "176", "BR, Banco Central do Brazil" },
		{ "177", "AU, LIFA (Life Insurance Federation of Australia)" },
		{ "178", "AU, SAA (Standards Association of Australia)" },
		{ "179", "US, Air transport association of America" },
		{ "180", "DE, BIA (Berufsgenossenschaftliches Institut fuer Arbeitssicherheit)" },
		{ "181", "Edibuild" },
		{ "182", "US, Standard Carrier Alpha Code (Motor)" },
		{ "183", "US, American Petroleum Institute" },
		{ "184", "AU, ACOS (Australian Chamber of Shipping)" },
		{ "185", "DE, BDI (Bundesverband der Deutschen Industrie e.V.)" },
		{ "186", "US, GSA (General Services Administration)" },
		{ "187", "US, DLMSO (Defense Logistics Management Standards Office)" },
		{ "188", "US, NIST (National Institute of Standards and Technology)" },
		{ "189", "US, DoD (Department of Defense)" },
		{ "190", "US, VA (Department of Veterans Affairs)" },
		{ "191", "IAPSO (United Nations Inter-Agency Procurement Services Office)" },
		{ "192", "Shipper's association" },
		{ "193", "EU, European Telecommunications Informatics Services (ETIS)" },
		{ "194", "AU, AQIS (Australian Quarantine and Inspection Service)" },
		{ "195", "CO, DIAN (Direccion de Impuestos y Aduanas Nacionales)" },
		{ "ZZZ", "Mutually defined" },
	};
}