using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace indice.Edi.Tests.Issue256.Qualifiers;

/// <summary>
/// Document/message name, coded
/// </summary>
public class DocumentMessageNameCoded
{
	/// <summary>
	/// String assign converter
	/// </summary>
	public static implicit operator DocumentMessageNameCoded(string s) => new DocumentMessageNameCoded { Code = s };

	/// <summary>
	/// Code of the value
	/// </summary>
	public string? Code { get; set; }

	/// <summary>
	/// Value converted from code
	/// </summary>
	public string? Value => Code is null ? null : (Qualifiers.ContainsKey(Code) ? Qualifiers[Code] : null);

	/// <summary>
	/// All possible values
	/// </summary>
	[JsonIgnore]
	public Dictionary<string, string> Qualifiers => new Dictionary<string, string>
	{
		{ "1", "Certificate of analysis" },
		{ "2", "Certificate of conformity" },
		{ "3", "Certificate of quality" },
		{ "4", "Test report" },
		{ "5", "Product performance report" },
		{ "6", "Product specification report" },
		{ "7", "Process data report" },
		{ "8", "First sample test report" },
		{ "9", "Price/sales catalogue" },
		{ "10", "Party information" },
		{ "11", "Federal label approval" },
		{ "12", "Mill certificate" },
		{ "13", "Post receipt" },
		{ "14", "Weight certificate" },
		{ "15", "Weight list" },
		{ "16", "Certificate" },
		{ "17", "Combined certificate of value and origin" },
		{ "18", "Movement certificate A.TR.1" },
		{ "19", "Certificate of quantity" },
		{ "20", "Quality data message" },
		{ "21", "Query" },
		{ "22", "Response to query" },
		{ "23", "Status information" },
		{ "24", "Restow" },
		{ "25", "Container discharger list" },
		{ "26", "Corporate superannuation contributions advice" },
		{ "27", "Industry superannuation contributions advice" },
		{ "28", "Corporate superannuation member maintenance message" },
		{ "29", "Industry superannuation member maintenance message" },
		{ "30", "Life insurance payroll deductions advice" },
		{ "31", "Underbond request" },
		{ "32", "Underbond approval" },
		{ "33", "Certificate of sealing of export meat lockers" },
		{ "34", "Cargo status" },
		{ "35", "Inventory report" },
		{ "36", "Identity card" },
		{ "37", "Response to a trade statistics message" },
		{ "38", "Vaccination certificate" },
		{ "39", "Passport" },
		{ "40", "Driving licence (national)" },
		{ "41", "Driving licence (international)" },
		{ "42", "Free pass" },
		{ "43", "Season ticket" },
		{ "44", "Transport status report" },
		{ "45", "Transport status request" },
		{ "47", "Extra-Community trade statistical declaration" },
		{ "48", "Written instructions in conformance with ADR article number 10385" },
		{ "49", "Damage certification" },
		{ "51", "Price/sales catalogue response" },
		{ "52", "Price negotiation result" },
		{ "53", "Safety and hazard data sheet" },
		{ "54", "Legal statement of an account" },
		{ "55", "Listing statement of an account" },
		{ "56", "Closing statement of an account" },
		{ "57", "Transport equipment on-hire report" },
		{ "58", "Transport equipment off-hire report" },
		{ "59", "Treatment - nil outturn" },
		{ "60", "Treatment - time-up underbond" },
		{ "61", "Treatment - underbond by sea" },
		{ "62", "Treatment - personal effect" },
		{ "63", "Treatment - timber" },
		{ "64", "Preliminary credit assessment" },
		{ "65", "Credit cover" },
		{ "66", "Current account" },
		{ "67", "Commercial dispute" },
		{ "68", "Chargeback" },
		{ "69", "Reassignment" },
		{ "70", "Collateral account" },
		{ "71", "Request for payment" },
		{ "72", "Unship permit" },
		{ "73", "Statistical definitions" },
		{ "74", "Statistical data" },
		{ "75", "Request for statistical data" },
		{ "76", "Call-off delivery" },
		{ "77", "Status report" },
		{ "78", "Inventory movement advice" },
		{ "79", "Inventory status advice" },
		{ "80", "Debit note related to goods or services" },
		{ "81", "Credit note related to goods or services" },
		{ "82", "Metered services invoice" },
		{ "83", "Credit note related to financial adjustments" },
		{ "84", "Debit note related to financial adjustments" },
		{ "85", "Customs manifest" },
		{ "86", "Vessel unpack report" },
		{ "87", "General cargo summary manifest report" },
		{ "88", "Consignment unpack report" },
		{ "89", "Meat and meat by-products sanitary certificate" },
		{ "90", "Meat food products sanitary certificate" },
		{ "91", "Poultry sanitary certificate" },
		{ "92", "Horsemeat sanitary certificate" },
		{ "93", "Casing sanitary certificate" },
		{ "94", "Pharmaceutical sanitary certificate" },
		{ "95", "Inedible sanitary certificate" },
		{ "96", "Impending arrival" },
		{ "97", "Means of transport advice" },
		{ "98", "Arrival information" },
		{ "99", "Cargo release notification" },
		{ "100", "Excise certificate" },
		{ "101", "Registration document" },
		{ "102", "Tax notification" },
		{ "103", "Transport equipment direct interchange report" },
		{ "104", "Transport equipment impending arrival advice" },
		{ "105", "Purchase order" },
		{ "106", "Transport equipment damage report" },
		{ "107", "Transport equipment maintenance and repair work estimate advice" },
		{ "108", "Transport equipment empty release instruction" },
		{ "109", "Transport movement gate in report" },
		{ "110", "Manufacturing instructions" },
		{ "111", "Transport movement gate out report" },
		{ "112", "Transport equipment unpacking instruction" },
		{ "113", "Transport equipment unpacking report" },
		{ "114", "Transport equipment pick-up availability request" },
		{ "115", "Transport equipment pick-up availability confirmation" },
		{ "116", "Transport equipment pick-up report" },
		{ "117", "Transport equipment shift report" },
		{ "118", "Transport discharge instruction" },
		{ "119", "Transport discharge report" },
		{ "120", "Stores requisition" },
		{ "121", "Transport loading instruction" },
		{ "122", "Transport loading report" },
		{ "123", "Transport equipment maintenance and repair work authorisation" },
		{ "124", "Transport departure report" },
		{ "125", "Transport empty equipment advice" },
		{ "126", "Transport equipment acceptance order" },
		{ "127", "Transport equipment special service instruction" },
		{ "128", "Transport equipment stock report" },
		{ "129", "Transport cargo release order" },
		{ "130", "Invoicing data sheet" },
		{ "131", "Transport equipment packing instruction" },
		{ "132", "Customs clearance notice" },
		{ "133", "Customs documents expiration notice" },
		{ "134", "Transport equipment on-hire request" },
		{ "135", "Transport equipment on-hire order" },
		{ "136", "Transport equipment off-hire request" },
		{ "137", "Transport equipment survey order" },
		{ "138", "Transport equipment survey order response" },
		{ "139", "Transport equipment survey report" },
		{ "140", "Packing instructions" },
		{ "142", "Transport equipment maintenance and repair work estimate order" },
		{ "143", "Transport equipment maintenance and repair notice" },
		{ "144", "Empty container disposition order" },
		{ "145", "Cargo vessel discharge order" },
		{ "146", "Cargo vessel loading order" },
		{ "147", "Multidrop order" },
		{ "148", "Bailment contract" },
		{ "149", "Basic agreement" },
		{ "150", "Internal transport order" },
		{ "151", "Grant" },
		{ "152", "Indefinite delivery indefinite quantity contract" },
		{ "153", "Indefinite delivery definite quantity contract" },
		{ "154", "Requirements contract" },
		{ "155", "Task order" },
		{ "156", "Make or buy plan" },
		{ "157", "Subcontractor plan" },
		{ "158", "Cost data summary" },
		{ "159", "Certified cost and price data" },
		{ "160", "Wage determination" },
		{ "161", "Contract Funds Status Report (CFSR)" },
		{ "162", "Certified inspection and test results" },
		{ "163", "Material inspection and receiving report" },
		{ "164", "Purchasing specification" },
		{ "165", "Payment or performance bond" },
		{ "166", "Contract security classification specification" },
		{ "167", "Manufacturing specification" },
		{ "168", "Buy America certificate of compliance" },
		{ "169", "Container off-hire notice" },
		{ "170", "Cargo acceptance order" },
		{ "171", "Pick-up notice" },
		{ "172", "Authorisation to plan and suggest orders" },
		{ "173", "Authorisation to plan and ship orders" },
		{ "174", "Drawing" },
		{ "175", "Cost Performance Report (CPR) format 2" },
		{ "176", "Cost Schedule Status Report (CSSR)" },
		{ "177", "Cost Performance Report (CPR) format 1" },
		{ "178", "Cost Performance Report (CPR) format 3" },
		{ "179", "Cost Performance Report (CPR) format 4" },
		{ "180", "Cost Performance Report (CPR) format 5" },
		{ "181", "Progressive discharge report" },
		{ "182", "Balance confirmation" },
		{ "183", "Container stripping order" },
		{ "184", "Container stuffing order" },
		{ "190", "Statistical and other administrative internal documents" },
		{ "201", "Direct payment valuation request" },
		{ "202", "Direct payment valuation" },
		{ "203", "Provisional payment valuation" },
		{ "204", "Payment valuation" },
		{ "205", "Quantity valuation" },
		{ "206", "Quantity valuation request" },
		{ "207", "Contract bill of quantities - BOQ" },
		{ "208", "Unpriced tender BOQ" },
		{ "209", "Priced tender BOQ" },
		{ "210", "Enquiry" },
		{ "211", "Interim application for payment" },
		{ "212", "Agreement to pay" },
		{ "215", "Letter of intent" },
		{ "220", "Order" },
		{ "221", "Blanket order" },
		{ "222", "Spot order" },
		{ "223", "Lease order" },
		{ "224", "Rush order" },
		{ "225", "Repair order" },
		{ "226", "Call off order" },
		{ "227", "Consignment order" },
		{ "228", "Sample order" },
		{ "229", "Swap order" },
		{ "230", "Purchase order change request" },
		{ "231", "Purchase order response" },
		{ "232", "Hire order" },
		{ "233", "Spare parts order" },
		{ "240", "Delivery instructions" },
		{ "241", "Delivery schedule" },
		{ "242", "Delivery just-in-time" },
		{ "245", "Delivery release" },
		{ "270", "Delivery note" },
		{ "271", "Packing list" },
		{ "310", "Offer/quotation" },
		{ "311", "Request for quote" },
		{ "315", "Contract" },
		{ "320", "Acknowledgement of order" },
		{ "325", "Proforma invoice" },
		{ "326", "Partial invoice" },
		{ "327", "Operating instructions" },
		{ "328", "Name/product plate" },
		{ "330", "Request for delivery instructions" },
		{ "335", "Booking request" },
		{ "340", "Shipping instructions" },
		{ "341", "Shipper's letter of instructions (air)" },
		{ "343", "Cartage order (local transport)" },
		{ "345", "Ready for despatch advice" },
		{ "350", "Despatch order" },
		{ "351", "Despatch advice" },
		{ "370", "Advice of distribution of documents" },
		{ "380", "Commercial invoice" },
		{ "381", "Credit note" },
		{ "382", "Commission note" },
		{ "383", "Debit note" },
		{ "384", "Corrected invoice" },
		{ "385", "Consolidated invoice" },
		{ "386", "Prepayment invoice" },
		{ "387", "Hire invoice" },
		{ "388", "Tax invoice" },
		{ "389", "Self-billed invoice" },
		{ "390", "Delcredere invoice" },
		{ "393", "Factored invoice" },
		{ "394", "Lease invoice" },
		{ "395", "Consignment invoice" },
		{ "396", "Factored credit note" },
		{ "409", "Instructions for bank transfer" },
		{ "412", "Application for banker's draft" },
		{ "425", "Collection payment advice" },
		{ "426", "Documentary credit payment advice" },
		{ "427", "Documentary credit acceptance advice" },
		{ "428", "Documentary credit negotiation advice" },
		{ "429", "Application for banker's guarantee" },
		{ "430", "Banker's guarantee" },
		{ "431", "Documentary credit letter of indemnity" },
		{ "435", "Preadvice of a credit" },
		{ "447", "Collection order" },
		{ "448", "Documents presentation form" },
		{ "450", "Payment order" },
		{ "451", "Extended payment order" },
		{ "452", "Multiple payment order" },
		{ "454", "Credit advice" },
		{ "455", "Extended credit advice" },
		{ "456", "Debit advice" },
		{ "457", "Reversal of debit" },
		{ "458", "Reversal of credit" },
		{ "460", "Documentary credit application" },
		{ "465", "Documentary credit" },
		{ "466", "Documentary credit notification" },
		{ "467", "Documentary credit transfer advice" },
		{ "468", "Documentary credit amendment notification" },
		{ "469", "Documentary credit amendment" },
		{ "481", "Remittance advice" },
		{ "485", "Banker's draft" },
		{ "490", "Bill of exchange" },
		{ "491", "Promissory note" },
		{ "492", "Financial statement of account" },
		{ "493", "Statement of account message" },
		{ "520", "Insurance certificate" },
		{ "530", "Insurance policy" },
		{ "550", "Insurance declaration sheet (bordereau)" },
		{ "575", "Insurer's invoice" },
		{ "580", "Cover note" },
		{ "610", "Forwarding instructions" },
		{ "621", "Forwarder's advice to import agent" },
		{ "622", "Forwarder's advice to exporter" },
		{ "623", "Forwarder's invoice" },
		{ "624", "Forwarder's certificate of receipt" },
		{ "630", "Shipping note" },
		{ "631", "Forwarder's warehouse receipt" },
		{ "632", "Goods receipt" },
		{ "633", "Port charges documents" },
		{ "635", "Warehouse warrant" },
		{ "640", "Delivery order" },
		{ "650", "Handling order" },
		{ "655", "Gate pass" },
		{ "700", "Waybill" },
		{ "701", "Universal (multipurpose) transport document" },
		{ "702", "Goods receipt, carriage" },
		{ "703", "House waybill" },
		{ "704", "Master bill of lading" },
		{ "705", "Bill of lading" },
		{ "706", "Bill of lading original" },
		{ "707", "Bill of lading copy" },
		{ "708", "Empty container bill" },
		{ "709", "Tanker bill of lading" },
		{ "710", "Sea waybill" },
		{ "711", "Inland waterway bill of lading" },
		{ "712", "Non-negotiable maritime transport document (generic)" },
		{ "713", "Mate's receipt" },
		{ "714", "House bill of lading" },
		{ "715", "Letter of indemnity for non-surrender of bill of lading" },
		{ "716", "Forwarder's bill of lading" },
		{ "720", "Rail consignment note (generic term)" },
		{ "722", "Road list-SMGS" },
		{ "723", "Escort official recognition" },
		{ "724", "Recharging document" },
		{ "730", "Road consignment note" },
		{ "740", "Air waybill" },
		{ "741", "Master air waybill" },
		{ "743", "Substitute air waybill" },
		{ "744", "Crew's effects declaration" },
		{ "745", "Passenger list" },
		{ "746", "Delivery notice (rail transport)" },
		{ "750", "Despatch note (post parcels)" },
		{ "760", "Multimodal/combined transport document (generic)" },
		{ "761", "Through bill of lading" },
		{ "763", "Forwarder's certificate of transport" },
		{ "764", "Combined transport document (generic)" },
		{ "765", "Multimodal transport document (generic)" },
		{ "766", "Combined transport bill of lading/multimodal bill of lading" },
		{ "770", "Booking confirmation" },
		{ "775", "Calling forward notice" },
		{ "780", "Freight invoice" },
		{ "781", "Arrival notice (goods)" },
		{ "782", "Notice of circumstances preventing delivery (goods)" },
		{ "783", "Notice of circumstances preventing transport (goods)" },
		{ "784", "Delivery notice (goods)" },
		{ "785", "Cargo manifest" },
		{ "786", "Freight manifest" },
		{ "787", "Bordereau" },
		{ "788", "Container manifest (unit packing list)" },
		{ "789", "Charges note" },
		{ "790", "Advice of collection" },
		{ "791", "Safety of ship certificate" },
		{ "792", "Safety of radio certificate" },
		{ "793", "Safety of equipment certificate" },
		{ "794", "Civil liability for oil certificate" },
		{ "795", "Loadline document" },
		{ "796", "Derat document" },
		{ "797", "Maritime declaration of health" },
		{ "798", "Certificate of registry" },
		{ "799", "Ship's stores declaration" },
		{ "810", "Export licence, application for" },
		{ "811", "Export licence" },
		{ "812", "Exchange control declaration, export" },
		{ "820", "Despatch note model T" },
		{ "821", "Despatch note model T1" },
		{ "822", "Despatch note model T2" },
		{ "823", "Control document T5" },
		{ "824", "Re-sending consignment note" },
		{ "825", "Despatch note model T2L" },
		{ "830", "Goods declaration for exportation" },
		{ "833", "Cargo declaration (departure)" },
		{ "840", "Application for goods control certificate" },
		{ "841", "Goods control certificate" },
		{ "850", "Application for phytosanitary certificate" },
		{ "851", "Phytosanitary certificate" },
		{ "852", "Sanitary certificate" },
		{ "853", "Veterinary certificate" },
		{ "855", "Application for inspection certificate" },
		{ "856", "Inspection certificate" },
		{ "860", "Certificate of origin, application for" },
		{ "861", "Certificate of origin" },
		{ "862", "Declaration of origin" },
		{ "863", "Regional appellation certificate" },
		{ "864", "Preference certificate of origin" },
		{ "865", "Certificate of origin form GSP" },
		{ "870", "Consular invoice" },
		{ "890", "Dangerous goods declaration" },
		{ "895", "Statistical document, export" },
		{ "896", "INTRASTAT declaration" },
		{ "901", "Delivery verification certificate" },
		{ "910", "Import licence, application for" },
		{ "911", "Import licence" },
		{ "913", "Customs declaration without commercial detail" },
		{ "914", "Customs declaration with commercial and item detail" },
		{ "915", "Customs declaration without item detail" },
		{ "916", "Related document" },
		{ "917", "Receipt (Customs)" },
		{ "925", "Application for exchange allocation" },
		{ "926", "Foreign exchange permit" },
		{ "927", "Exchange control declaration (import)" },
		{ "929", "Goods declaration for importation" },
		{ "930", "Goods declaration for home use" },
		{ "931", "Customs immediate release declaration" },
		{ "932", "Customs delivery note" },
		{ "933", "Cargo declaration (arrival)" },
		{ "934", "Value declaration" },
		{ "935", "Customs invoice" },
		{ "936", "Customs declaration (post parcels)" },
		{ "937", "Tax declaration (value added tax)" },
		{ "938", "Tax declaration (general)" },
		{ "940", "Tax demand" },
		{ "941", "Embargo permit" },
		{ "950", "Goods declaration for Customs transit" },
		{ "951", "TIF form" },
		{ "952", "TIR carnet" },
		{ "953", "EC carnet" },
		{ "954", "EUR 1 certificate of origin" },
		{ "955", "ATA carnet" },
		{ "960", "Single administrative document" },
		{ "961", "General response (Customs)" },
		{ "962", "Document response (Customs)" },
		{ "963", "Error response (Customs)" },
		{ "964", "Package response (Customs)" },
		{ "965", "Tax calculation/confirmation response (Customs)" },
		{ "966", "Quota prior allocation certificate" },
		{ "990", "End use authorization" },
		{ "991", "Government contract" },
		{ "995", "Statistical document, import" },
		{ "996", "Application for documentary credit" },
		{ "998", "Previous Customs document/message" },
	};
}