using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace indice.Edi.Tests.Issue256.Qualifiers;

/// <summary>
/// Party qualifier
/// </summary>
public class PartyQualifier
{
	/// <summary>
	/// String assign converter
	/// </summary>
	public static implicit operator PartyQualifier(string s) => new PartyQualifier { Code = s };

	/// <summary>
	/// Code of the value
	/// </summary>
	public string? Code { get; set; }

	/// <summary>
	/// Value converted from code
	/// </summary>
	public string? Value => Code is null ? null : (Qualifiers.ContainsKey(Code) ? Qualifiers[Code] : null);

	/// <summary>
	/// All possible values
	/// </summary>
	[JsonIgnore]
	public Dictionary<string, string> Qualifiers => new Dictionary<string, string>
	{
		{ "AA", "Party to be billed (AAR Accounting rule 11)" },
		{ "AB", "Buyer's agent/representative" },
		{ "AE", "Declarant's agent/representative" },
		{ "AF", "Transit principal" },
		{ "AG", "Agent/representative" },
		{ "AH", "Transit principal's agent/representative" },
		{ "AI", "Successful job applicant" },
		{ "AJ", "Party issuing mutually agreed codes" },
		{ "AK", "Acknowledgement recipient" },
		{ "AL", "Principal" },
		{ "AM", "Authorized official" },
		{ "AN", "Approved importer" },
		{ "AO", "Account of" },
		{ "AP", "Accepting party" },
		{ "AQ", "Approved consignor" },
		{ "AR", "Authorized exporter" },
		{ "AS", "Account servicing financial institution" },
		{ "AT", "Authorized importer" },
		{ "AU", "Authorized trader (transit)" },
		{ "AV", "Authorizing official" },
		{ "AW", "Applicant's bank" },
		{ "AX", "Authenticating party" },
		{ "AY", "Animal being investigated" },
		{ "AZ", "Issuing bank" },
		{ "B1", "Contact bank 1" },
		{ "B2", "Contact bank 2" },
		{ "BA", "Booking agent" },
		{ "BB", "Buyer's bank" },
		{ "BC", "Negotiating bank" },
		{ "BD", "Documentary credit reimbursing bank" },
		{ "BE", "Beneficiary" },
		{ "BF", "Beneficiary's bank" },
		{ "BG", "Employer" },
		{ "BH", "Previous employer" },
		{ "BI", "Buyer's financial institution" },
		{ "BJ", "Release to party" },
		{ "BK", "Financial institution" },
		{ "BL", "Bill of lading recipient" },
		{ "BM", "Insured" },
		{ "BN", "Insurance beneficiary" },
		{ "BO", "Broker or sales office" },
		{ "BP", "Building site purchaser" },
		{ "BQ", "Cheque drawn bank" },
		{ "BS", "Bill and ship to" },
		{ "BT", "Party to be billed for other than freight (bill to)" },
		{ "BU", "Service bureau" },
		{ "BV", "Member" },
		{ "BW", "Borrower" },
		{ "BX", "Building site engineer" },
		{ "BY", "Buyer" },
		{ "BZ", "Building site forwarder" },
		{ "C1", "In care of party no. 1" },
		{ "C2", "In care of party no. 2" },
		{ "CA", "Carrier" },
		{ "CB", "Customs broker" },
		{ "CC", "Claimant" },
		{ "CD", "Agent's bank" },
		{ "CE", "Ceding company" },
		{ "CF", "Container operator/lessee" },
		{ "CG", "Carrier's agent" },
		{ "CH", "Connecting carrier" },
		{ "CI", "Commission processor" },
		{ "CJ", "Previous member" },
		{ "CK", "Empty equipment despatch party" },
		{ "CL", "Container location party" },
		{ "CM", "Customs" },
		{ "CN", "Consignee" },
		{ "CO", "Corporate office" },
		{ "CP", "Party to receive certificate of compliance" },
		{ "CQ", "Cheque order" },
		{ "CR", "Empty equipment return party" },
		{ "CS", "Consolidator" },
		{ "CT", "Consignee to be specified" },
		{ "CU", "Container return company" },
		{ "CV", "Consignee of vessel" },
		{ "CW", "Equipment owner" },
		{ "CX", "Consignee's agent" },
		{ "CY", "Commissionable agent" },
		{ "CZ", "Consignor" },
		{ "DA", "Available with bank (documentary credits)" },
		{ "DB", "Distributor branch" },
		{ "DC", "Deconsolidator" },
		{ "DD", "Documentary credit account party's bank" },
		{ "DE", "Depositor" },
		{ "DF", "Documentary credit applicant" },
		{ "DG", "Documentary credit beneficiary" },
		{ "DH", "Documentary credit account party" },
		{ "DI", "Documentary credit second beneficiary" },
		{ "DJ", "Party according to documentary credit transaction" },
		{ "DK", "Documentary credit beneficiary's bank" },
		{ "DL", "Factor" },
		{ "DM", "Party to whom documents are to be presented" },
		{ "DN", "Owner of operation" },
		{ "DO", "Document recipient" },
		{ "DP", "Delivery party" },
		{ "DQ", "Owner's agent" },
		{ "DR", "Driver" },
		{ "DS", "Distributor" },
		{ "DT", "Declarant" },
		{ "DU", "Owner's representative" },
		{ "DV", "Project management office" },
		{ "DW", "Drawee" },
		{ "DX", "Engineer (construction)" },
		{ "DY", "Engineer, resident (construction)" },
		{ "DZ", "Architect" },
		{ "EA", "Architect-designer" },
		{ "EB", "Building inspectorate" },
		{ "EC", "Exchanger" },
		{ "ED", "Engineer, consultant" },
		{ "EE", "Location of goods for customs examination before clearance" },
		{ "EF", "Project coordination office" },
		{ "EG", "Surveyor, topographical" },
		{ "EH", "Engineer, measurement" },
		{ "EI", "Controller, quality" },
		{ "EJ", "Surveyor, quantity" },
		{ "EK", "Surveyor (professional), quantity" },
		{ "EL", "Project" },
		{ "EM", "Party to receive electronic memo of invoice" },
		{ "EN", "Tenderer" },
		{ "EO", "Owner of equipment" },
		{ "EP", "Equipment drop-off party" },
		{ "EQ", "Empty container responsible party" },
		{ "ER", "Empty container return agent" },
		{ "ES", "Contractor, lead" },
		{ "ET", "Co-contractor" },
		{ "EU", "Contractor, general" },
		{ "EV", "Subcontractor" },
		{ "EW", "Subcontractor with direct payment" },
		{ "EX", "Exporter" },
		{ "EY", "Subcontractor, nominated" },
		{ "EZ", "Operator, essential services" },
		{ "FA", "Operator, communication channel" },
		{ "FB", "Nominated freight company" },
		{ "FC", "Contractor, main" },
		{ "FD", "Buyer's parent company" },
		{ "FE", "Credit rating agency" },
		{ "FF", "Factor, correspondent" },
		{ "FG", "Buyer as officially registered" },
		{ "FH", "Seller as officially registered" },
		{ "FI", "Copy message to" },
		{ "FJ", "Trade Union" },
		{ "FK", "Previous Trade Union" },
		{ "FL", "Passenger" },
		{ "FM", "Crew member" },
		{ "FN", "Tariff issuer" },
		{ "FO", "Party performing inspection" },
		{ "FP", "Freight/charges payer" },
		{ "FQ", "Container survey agent" },
		{ "FR", "Message from" },
		{ "FS", "Party authorized to make definite a contract action" },
		{ "FT", "Party responsible for financial settlement" },
		{ "FU", "Hazardous material office" },
		{ "FV", "Party providing government furnished property" },
		{ "FW", "Freight forwarder" },
		{ "FX", "Current receiver" },
		{ "FY", "Current sender" },
		{ "FZ", "Grouping centre" },
		{ "GA", "Road carrier" },
		{ "GB", "Chamber of commerce" },
		{ "GC", "Goods custodian" },
		{ "GD", "Producer" },
		{ "GE", "Registration tribunal" },
		{ "GF", "Slot charter party" },
		{ "GG", "Warehouse" },
		{ "GH", "Applicant for job" },
		{ "GI", "Spouse" },
		{ "GJ", "Mother" },
		{ "GK", "Father" },
		{ "GL", "Socially insured person" },
		{ "GM", "Inventory controller" },
		{ "GN", "Processor" },
		{ "GO", "Goods owner" },
		{ "GP", "Packer" },
		{ "GQ", "Slaughterer" },
		{ "GR", "Goods releaser" },
		{ "GS", "Consignor's representative" },
		{ "GT", "Rail carrier" },
		{ "GU", "Originator of article number" },
		{ "GV", "Procurement responsibility for order" },
		{ "GW", "Party fulfilling all operations" },
		{ "GX", "Central catalogue party" },
		{ "GY", "Inventory reporting party" },
		{ "GZ", "Substitute supplier" },
		{ "HA", "Party which delivers consignments to the terminal" },
		{ "HB", "Party which picks up consignments from the terminal" },
		{ "HC", "Transit freight forwarder" },
		{ "HD", "Inspection and acceptance party" },
		{ "HE", "Transportation office" },
		{ "HF", "Contract administration office" },
		{ "HG", "Investigator" },
		{ "HH", "Audit office" },
		{ "HI", "Requestor" },
		{ "HJ", "Foreign disclosure information office" },
		{ "HK", "Mark-for party" },
		{ "HL", "Party to receive reports" },
		{ "HM", "Alternative manufacturer" },
		{ "HN", "Service performer" },
		{ "HO", "Shipper's association" },
		{ "HP", "Final message recipient" },
		{ "HQ", "Account owner" },
		{ "HR", "Shipping line service" },
		{ "I1", "Intermediary bank 1" },
		{ "I2", "Intermediary bank 2" },
		{ "IB", "Intermediary/broker" },
		{ "IC", "Intermediate consignee" },
		{ "ID", "Replacing manufacturer" },
		{ "IE", "Non-resident third party company with whom financial account is held" },
		{ "IF", "Non-resident group company with whom financial account is held" },
		{ "IG", "Non-resident beneficiary" },
		{ "IH", "Resident beneficiary" },
		{ "II", "Issuer of invoice" },
		{ "IJ", "Non-resident instructing party" },
		{ "IL", "Resident instructing party" },
		{ "IM", "Importer" },
		{ "IN", "Insurer" },
		{ "IO", "Insurance company" },
		{ "IP", "Insurance claim adjuster" },
		{ "IQ", "Domestic financial institution" },
		{ "IR", "Non-domestic financial institution" },
		{ "IS", "Party to receive certified inspection report" },
		{ "IT", "Installation on site" },
		{ "IU", "Non-resident debtor" },
		{ "IV", "Invoicee" },
		{ "IW", "Non-resident creditor" },
		{ "LA", "Party designated to provide living animal care" },
		{ "LB", "Coproducer" },
		{ "LN", "Lender" },
		{ "LP", "Loading party" },
		{ "MA", "Party for whom item is ultimately intended" },
		{ "MF", "Manufacturer of goods" },
		{ "MG", "Party designated to execute re-icing" },
		{ "MI", "Planning schedule/material release issuer" },
		{ "MP", "Manufacturing plant" },
		{ "MR", "Message recipient" },
		{ "MS", "Document/message issuer/sender" },
		{ "MT", "Party designated to execute sanitary procedures" },
		{ "N1", "Notify party no. 1" },
		{ "N2", "Notify party no. 2" },
		{ "NI", "Notify party" },
		{ "OA", "Break bulk berth operator" },
		{ "OB", "Ordered by" },
		{ "OF", "On behalf of" },
		{ "OI", "Outside inspection agency" },
		{ "OO", "Order of shipper" },
		{ "OP", "Operator of property or unit" },
		{ "OR", "Ordered bank" },
		{ "OS", "Original shipper" },
		{ "OT", "Outside test agency" },
		{ "OV", "Owner of means of transport" },
		{ "OY", "Ordering customer" },
		{ "P1", "Contact party 1" },
		{ "P2", "Contact party 2" },
		{ "P3", "Contact party 3" },
		{ "P4", "Contact party 4" },
		{ "PA", "Party to receive inspection report" },
		{ "PB", "Paying financial institution" },
		{ "PC", "Actual purchaser's customer" },
		{ "PD", "Purchaser's department buyer" },
		{ "PE", "Payee" },
		{ "PF", "Party to receive freight bill" },
		{ "PG", "Prime contractor" },
		{ "PH", "Payer's financial institution" },
		{ "PI", "Payee's company name/ID" },
		{ "PJ", "Party to receive correspondence" },
		{ "PK", "Contact party" },
		{ "PL", "Payor" },
		{ "PM", "Party to receive paper memo of invoice" },
		{ "PN", "Party to receive shipping notice" },
		{ "PO", "Ordering party" },
		{ "PQ", "Certifying party" },
		{ "PR", "Payer" },
		{ "PS", "Payer's company name/ID (Check, Draft or Wire)" },
		{ "PT", "Party to receive test report" },
		{ "PW", "Despatch party" },
		{ "PX", "Party to receive all documents" },
		{ "PY", "Checking party" },
		{ "PZ", "Party to print some document" },
		{ "RA", "Central bank or regulatory authority" },
		{ "RB", "Receiving financial institution" },
		{ "RE", "Party to receive commercial invoice remittance" },
		{ "RF", "Received from" },
		{ "RH", "Seller's financial institution" },
		{ "RI", "Reinsurance intermediary/broker" },
		{ "RL", "Reporting carrier (Customs)" },
		{ "RM", "Reporting carrier's nominated agent/representative (Customs)" },
		{ "RP", "Routing party" },
		{ "RS", "Party to receive statement of account" },
		{ "RV", "Receiver of cheque" },
		{ "RW", "Issuer of waybill" },
		{ "SB", "Sales responsibility" },
		{ "SE", "Seller" },
		{ "SF", "Ship from" },
		{ "SG", "Store group" },
		{ "SI", "Shipping schedule issuer" },
		{ "SK", "Plant" },
		{ "SN", "Store keeper" },
		{ "SO", "Sold to if different than bill to" },
		{ "SR", "Seller's agent/representative" },
		{ "SS", "Social securities collector's office" },
		{ "ST", "Ship to" },
		{ "SU", "Supplier" },
		{ "SX", "Surety for additions" },
		{ "SY", "Surety" },
		{ "SZ", "Surety for antidumping/countervailing duty" },
		{ "TC", "Tax collector's office" },
		{ "TD", "Party to receive technical documentation" },
		{ "TR", "Terminal operator" },
		{ "TS", "Party to receive certified test results" },
		{ "TT", "Transfer to" },
		{ "UC", "Ultimate consignee" },
		{ "UD", "Ultimate customer" },
		{ "UP", "Unloading party" },
		{ "VN", "Vendor" },
		{ "WD", "Warehouse depositor" },
		{ "WH", "Warehouse keeper" },
		{ "WM", "Works manager" },
		{ "WS", "Wholesaler" },
		{ "XX", "No heading" },
		{ "COP", "Convoying party" },
		{ "CPD", "Charges payer at destination" },
		{ "DCP", "Despatch charge payer" },
		{ "TCP", "Transit charge payer" },
		{ "UHP", "Unexpected handling party" },
		{ "WPA", "Weighting party" },
		{ "ZZZ", "Mutually defined" },
	};
}