using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace indice.Edi.Tests.Issue256.Qualifiers;

/// <summary>
/// Property measured, coded
/// </summary>
public class PropertyMeasuredCoded
{
	/// <summary>
	/// String assign converter
	/// </summary>
	public static implicit operator PropertyMeasuredCoded(string s) => new PropertyMeasuredCoded { Code = s };

	/// <summary>
	/// Code of the value
	/// </summary>
	public string? Code { get; set; }

	/// <summary>
	/// Value converted from code
	/// </summary>
	public string? Value => Code is null ? null : (Qualifiers.ContainsKey(Code) ? Qualifiers[Code] : null);

	/// <summary>
	/// All possible values
	/// </summary>
	[JsonIgnore]
	public Dictionary<string, string> Qualifiers => new Dictionary<string, string>
	{
		{ "A", "Consolidated weight" },
		{ "B", "Billed weight" },
		{ "D", "Destination weight agreement" },
		{ "E", "Estimated new weight" },
		{ "F", "Deficit weight" },
		{ "G", "Gross weight" },
		{ "L", "Legal weight" },
		{ "M", "Minimum weight" },
		{ "N", "Actual net weight" },
		{ "T", "Tare weight" },
		{ "U", "Weight per unit" },
		{ "AF", "Angle of bend" },
		{ "BL", "Breaking load" },
		{ "BR", "Brightness" },
		{ "BS", "Breaking strength" },
		{ "BW", "Basis weight" },
		{ "CM", "Color" },
		{ "CT", "Contents of package" },
		{ "CV", "Commercial weight" },
		{ "CZ", "Core length" },
		{ "DI", "Diameter" },
		{ "DL", "Delta value L" },
		{ "DN", "Density" },
		{ "DP", "Depth" },
		{ "DR", "Denier" },
		{ "DS", "Distance between points" },
		{ "DW", "Width, boxcar door" },
		{ "EA", "Elongation" },
		{ "FI", "Filament count" },
		{ "FL", "Longitudinal flatness" },
		{ "FN", "Flatness" },
		{ "FV", "Transverse flatness" },
		{ "GG", "Gauge" },
		{ "GW", "Gross weight, maximum" },
		{ "HF", "Hardness" },
		{ "HM", "Height, maximum" },
		{ "HT", "Height dimension" },
		{ "IB", "Impact energy" },
		{ "ID", "Inside diameter" },
		{ "LM", "Length, maximum" },
		{ "LN", "Length dimension" },
		{ "MO", "Moisture" },
		{ "MW", "Maximum weight" },
		{ "OD", "Outside diameter" },
		{ "RA", "Relative humidity" },
		{ "RF", "Resistivity" },
		{ "RJ", "Rockwell C" },
		{ "RP", "Reduction of area" },
		{ "RY", "Ratio" },
		{ "SQ", "Shipped quantity" },
		{ "TC", "Temperature" },
		{ "TH", "Thickness" },
		{ "TN", "Time period" },
		{ "TT", "Time" },
		{ "VH", "Height, van door" },
		{ "VW", "Width, van door" },
		{ "WA", "Weight per unit of area" },
		{ "WD", "Width dimension" },
		{ "WM", "Width, maximum" },
		{ "WT", "Weight" },
		{ "WU", "Weight per unit of length" },
		{ "XH", "Side height, flat bed with removable sides" },
		{ "XQ", "Squareness" },
		{ "XZ", "Spool size" },
		{ "YS", "Yield stress" },
		{ "ZB", "Boron" },
		{ "ZC", "Carbon" },
		{ "ZH", "Hydrogen" },
		{ "ZK", "Potassium" },
		{ "ZN", "Nitrogen" },
		{ "ZO", "Oxygen" },
		{ "ZP", "Phosphorus" },
		{ "ZS", "Sulphur" },
		{ "ZV", "Vanadium" },
		{ "ZW", "Tungsten" },
		{ "AAA", "Unit net weight" },
		{ "AAB", "Unit gross weight" },
		{ "AAC", "Total net weight" },
		{ "AAD", "Total gross weight" },
		{ "AAE", "Item gross weight" },
		{ "AAF", "Net net weight" },
		{ "AAG", "Gross weight (item level)" },
		{ "AAH", "Customs line item measurement" },
		{ "AAI", "Visa quantity" },
		{ "AAL", "Net weight" },
		{ "AAM", "Gross tonnage of the vessel" },
		{ "AAN", "Net tonnage of the vessel" },
		{ "AAO", "Humidity" },
		{ "AAP", "Voltage" },
		{ "AAQ", "Power consumption" },
		{ "AAR", "Heat dissipation" },
		{ "AAS", "Air flow" },
		{ "AAT", "Shock impact" },
		{ "AAU", "Operative temperature" },
		{ "AAV", "Non operative temperature" },
		{ "AAW", "Gross volume" },
		{ "AAX", "Net volume" },
		{ "AAY", "Water content" },
		{ "AAZ", "Tensile stress" },
		{ "ABA", "Fibrosity" },
		{ "ABB", "Gauge length" },
		{ "ABC", "Radius" },
		{ "ABD", "Straightness" },
		{ "ABE", "Strain" },
		{ "ABF", "Test piece dimensions" },
		{ "ABG", "Average reading" },
		{ "ABH", "External dimension" },
		{ "ABI", "Internal dimension" },
		{ "ABJ", "Volume" },
		{ "ABK", "Loading meter" },
		{ "ABL", "Retail container dimension" },
		{ "ABM", "Retail container size" },
		{ "ABN", "Other US Government agency application" },
		{ "ABO", "Measurement" },
		{ "ABQ", "Percentage of alcohol (by volume)" },
		{ "ABR", "Dimensions total weight" },
		{ "ABS", "Item weight" },
		{ "ABU", "Licence (quantity deducted)" },
		{ "ABV", "Cargo loaded" },
		{ "ABW", "Cargo discharged" },
		{ "ABX", "Weight of conveyance" },
		{ "ABY", "Conveyance summer dead weight" },
		{ "ABZ", "Containerized cargo on vessel's weight" },
		{ "ACA", "Non-containerized cargo on vessel's weight" },
		{ "ACB", "1st specified tariff quantity" },
		{ "ACC", "2nd specified tariff quantity" },
		{ "ACD", "3rd specified tariff quantity" },
		{ "ACE", "Weight ascertained" },
		{ "ACF", "Chemistry" },
		{ "ACG", "Chargeable weight" },
		{ "ACH", "Core notch dimensions" },
		{ "ACI", "Core size" },
		{ "ACJ", "Decision result value" },
		{ "ACK", "Dimensional tolerance" },
		{ "ACL", "Discrete measurement value" },
		{ "ACM", "Dimension used in price extension" },
		{ "ACN", "Estimated gross weight" },
		{ "ACO", "Environmental conditions" },
		{ "ACP", "Estimated volume" },
		{ "ACQ", "Footage" },
		{ "ACR", "Interpolated value" },
		{ "ACS", "Vessel overall length" },
		{ "ACT", "Limited coil measurement" },
		{ "ACU", "Lift limitation" },
		{ "ACV", "Loading meters" },
		{ "ACW", "Number of axles" },
		{ "ACX", "Payload" },
		{ "ACY", "Parting cut (sawcut)" },
		{ "ACZ", "Physical dimensions" },
		{ "ADA", "Package limitations" },
		{ "ADB", "Platform limitation" },
		{ "ADC", "Receiving facility limitations" },
		{ "ADD", "Property specification" },
		{ "ADE", "Shipping tolerance" },
		{ "ADF", "Shade" },
		{ "ADG", "Storage limitation" },
		{ "ADH", "Surface roughness" },
		{ "ADI", "Surface treatment" },
		{ "ADJ", "Surface" },
		{ "ADK", "Specification value" },
		{ "ADL", "Transportation equipment limitations" },
		{ "ADM", "Test result" },
		{ "ADN", "Time used in price extension" },
		{ "ADO", "Observed value" },
		{ "ADP", "True value" },
		{ "ADQ", "Weight used in price extension" },
		{ "ADR", "Start position in the length" },
		{ "ADS", "End position in the length" },
		{ "ADT", "Start position in the width" },
		{ "ADU", "End position in the width" },
		{ "ADV", "Start position in the thickness" },
		{ "ADW", "End position in the thickness" },
		{ "ADX", "Transport container actual filling weight" },
		{ "ADY", "Transport container maximum capacity" },
		{ "ADZ", "Declared net weight" },
		{ "AEA", "Loading height" },
		{ "AEB", "Stacking height" },
		{ "AEC", "Calculated weight" },
		{ "AED", "Ferrite" },
		{ "AEE", "Impurity" },
		{ "AEF", "Grain size" },
		{ "AEG", "Lanthanides" },
		{ "AEH", "Elasticity" },
		{ "AEI", "Drained weight" },
		{ "AEJ", "Gallium" },
		{ "AEK", "Strontium" },
		{ "AEM", "Equipment storage limitation" },
		{ "BND", "Bands" },
		{ "BRA", "Brakes" },
		{ "BRE", "Break" },
		{ "BSW", "Breaking strength wet" },
		{ "CHN", "Change" },
		{ "LND", "Lost end" },
		{ "PRS", "Pre stretch" },
		{ "PTN", "Per tonne" },
		{ "RMW", "Ream weight" },
		{ "RUN", "Run (process)" },
		{ "ZAL", "Aluminium" },
		{ "ZAS", "Arsenic" },
		{ "ZBI", "Bismuth" },
		{ "ZCA", "Calcium" },
		{ "ZCB", "Columbium" },
		{ "ZCE", "Cerium" },
		{ "ZCL", "Chlorine" },
		{ "ZCO", "Cobalt" },
		{ "ZCR", "Chromium" },
		{ "ZCU", "Copper" },
		{ "ZFE", "Iron" },
		{ "ZFS", "Iron plus silicon" },
		{ "ZGE", "Germanium" },
		{ "ZMG", "Magnesium" },
		{ "ZMN", "Manganese" },
		{ "ZMO", "Molybdenum" },
		{ "ZNA", "Sodium" },
		{ "ZNB", "Niobium" },
		{ "ZNI", "Nickel" },
		{ "ZPB", "Lead" },
		{ "ZSB", "Antimony" },
		{ "ZSE", "Selenium" },
		{ "ZSI", "Silicon" },
		{ "ZSL", "Silicium oxyd" },
		{ "ZSN", "Tin" },
		{ "ZTA", "Tantalium" },
		{ "ZTE", "Tellurium" },
		{ "ZTI", "Titanium" },
		{ "ZWA", "Waste content" },
		{ "ZZN", "Zinc" },
		{ "ZZR", "Zirconium" },
		{ "ZZZ", "Mutually defined" },
	};
}