using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace indice.Edi.Tests.Issue256.Qualifiers;

/// <summary>
/// Quantity qualifier
/// </summary>
public class QuantityQualifier
{
	/// <summary>
	/// String assign converter
	/// </summary>
	public static implicit operator QuantityQualifier(string s) => new QuantityQualifier { Code = s };

	/// <summary>
	/// Code of the value
	/// </summary>
	public string? Code { get; set; }

	/// <summary>
	/// Value converted from code
	/// </summary>
	public string? Value => Code is null ? null : (Qualifiers.ContainsKey(Code) ? Qualifiers[Code] : null);

	/// <summary>
	/// All possible values
	/// </summary>
	[JsonIgnore]
	public Dictionary<string, string> Qualifiers => new Dictionary<string, string>
	{
		{ "1", "Discrete quantity" },
		{ "2", "Charge" },
		{ "3", "Cumulative quantity" },
		{ "8", "Inventory quantity at supplier's subject to inspection by customer" },
		{ "11", "Split quantity" },
		{ "12", "Despatch quantity" },
		{ "17", "Quantity on hand" },
		{ "18", "Previous quantity" },
		{ "20", "Unusable quantity" },
		{ "21", "Ordered quantity" },
		{ "22", "Quantity at 100%" },
		{ "23", "Active ingredient" },
		{ "24", "Inventory quantity at supplier's not subject to inspection by customer" },
		{ "25", "Retail sales" },
		{ "26", "Promotion quantity" },
		{ "27", "On hold for shipment" },
		{ "28", "Military sales quantity" },
		{ "29", "On premises sales" },
		{ "30", "Off premises sales" },
		{ "31", "Estimated annual volume" },
		{ "32", "Minimum delivery batch" },
		{ "33", "Maximum delivery batch" },
		{ "35", "Price break from" },
		{ "36", "Price break to" },
		{ "40", "Normal delivery" },
		{ "46", "Pieces delivered" },
		{ "47", "Invoiced quantity" },
		{ "48", "Received quantity" },
		{ "49", "Chargeable distance" },
		{ "50", "Disposition undetermined quantity" },
		{ "51", "Inventory category transfer" },
		{ "52", "Quantity per pack" },
		{ "53", "Minimum order quantity" },
		{ "54", "Maximum order quantity" },
		{ "55", "Total sales" },
		{ "56", "Wholesaler to wholesaler sales" },
		{ "57", "In transit quantity" },
		{ "58", "Quantity withdrawn" },
		{ "59", "Numbers of consumer units in the traded unit" },
		{ "60", "Current inventory quantity available for shipment" },
		{ "61", "Return quantity" },
		{ "62", "Sorted quantity" },
		{ "63", "Sorted quantity rejected" },
		{ "64", "Scrap quantity" },
		{ "65", "Destroyed quantity" },
		{ "66", "Committed quantity" },
		{ "67", "Estimated reading quantity" },
		{ "68", "End quantity" },
		{ "69", "Start quantity" },
		{ "70", "Cumulative quantity received" },
		{ "71", "Cumulative quantity ordered" },
		{ "72", "Cumulative quantity received end of prior year" },
		{ "73", "Outstanding quantity" },
		{ "74", "Latest cumulative quantity" },
		{ "75", "Previous highest cumulative quantity" },
		{ "76", "Adjusted corrector reading" },
		{ "77", "Work days" },
		{ "78", "Cumulative quantity scheduled" },
		{ "79", "Previous cumulative quantity" },
		{ "80", "Unadjusted corrector reading" },
		{ "81", "Extra unplanned delivery" },
		{ "82", "Quantity requirement for sample inspection" },
		{ "83", "Backorder quantity" },
		{ "84", "Urgent delivery quantity" },
		{ "85", "Previous order quantity to be cancelled" },
		{ "86", "Normal reading quantity" },
		{ "87", "Customer reading quantity" },
		{ "88", "Information reading quantity" },
		{ "89", "Quality control held" },
		{ "90", "As is quantity" },
		{ "91", "Open quantity" },
		{ "92", "Final delivery quantity" },
		{ "93", "Subsequent delivery quantity" },
		{ "94", "Substitutional quantity" },
		{ "95", "Redelivery after post processing" },
		{ "96", "Quality control failed" },
		{ "97", "Minimum inventory" },
		{ "98", "Maximum inventory" },
		{ "99", "Estimated quantity" },
		{ "100", "Chargeable weight" },
		{ "101", "Chargeable gross weight" },
		{ "102", "Chargeable tare weight" },
		{ "103", "Chargeable number of axles" },
		{ "104", "Chargeable number of containers" },
		{ "105", "Chargeable number of rail wagons" },
		{ "106", "Chargeable number of packages" },
		{ "107", "Chargeable number of units" },
		{ "108", "Chargeable period" },
		{ "109", "Chargeable volume" },
		{ "110", "Chargeable cubic measurements" },
		{ "111", "Chargeable surface" },
		{ "112", "Chargeable length" },
		{ "113", "Quantity to be delivered" },
		{ "114", "Number of passengers" },
		{ "115", "Number of crew" },
		{ "116", "Number of transport documents" },
		{ "117", "Quantity landed" },
		{ "118", "Quantity manifested" },
		{ "119", "Short shipped" },
		{ "120", "Split shipment" },
		{ "121", "Over shipped" },
		{ "122", "Short-landed goods" },
		{ "123", "Surplus goods" },
		{ "124", "Damaged goods" },
		{ "125", "Pilferage goods" },
		{ "126", "Lost goods" },
		{ "127", "Report difference" },
		{ "128", "Quantity loaded" },
		{ "129", "Units per unit price" },
		{ "130", "Allowance" },
		{ "131", "Delivery quantity" },
		{ "132", "Cumulative quantity, preceding period, planned" },
		{ "133", "Cumulative quantity, preceding period, reached" },
		{ "134", "Cumulative quantity, actual planned" },
		{ "135", "Period quantity, planned" },
		{ "136", "Period quantity, reached" },
		{ "137", "Cumulative quantity, preceding period, estimated" },
		{ "138", "Cumulative quantity, actual estimated" },
		{ "139", "Cumulative quantity, preceding period, measured" },
		{ "140", "Cumulative quantity, actual measured" },
		{ "141", "Period quantity, measured" },
		{ "142", "Total quantity, planned" },
		{ "143", "Quantity, remaining" },
		{ "144", "Tolerance" },
		{ "145", "Actual stock" },
		{ "146", "Model or target stock" },
		{ "147", "Direct shipment quantity" },
		{ "148", "Amortization total quantity" },
		{ "149", "Amortization order quantity" },
		{ "150", "Amortization cumulated quantity" },
		{ "151", "Quantity advised" },
		{ "152", "Quantity on hand" },
		{ "153", "Statistical sales quantity" },
		{ "154", "Sales quantity planned" },
		{ "155", "Replenishment quantity" },
		{ "156", "Inventory movement quantity" },
		{ "157", "Opening stock balance quantity" },
		{ "158", "Closing stock balance quantity" },
		{ "159", "Number of stops" },
		{ "160", "Minimum production batch" },
		{ "161", "Dimensional sample quantity" },
		{ "162", "Functional sample quantity" },
		{ "163", "Pre-production quantity" },
		{ "164", "Delivery batch" },
		{ "165", "Delivery batch multiple" },
		{ "166", "All time buy" },
		{ "167", "Total delivery quantity" },
		{ "168", "Single delivery quantity" },
		{ "169", "Supplied quantity" },
		{ "170", "Allocated quantity" },
		{ "171", "Maximum stackability" },
		{ "172", "Amortisation quantity" },
		{ "173", "Previously amortised quantity" },
		{ "174", "Total amortisation quantity" },
		{ "175", "Number of moulds" },
		{ "176", "Concurrent item output of tooling" },
		{ "177", "Periodic capacity of tooling" },
		{ "178", "Lifetime capacity of tooling" },
		{ "179", "Number of deliveries per despatch period" },
		{ "180", "Provided quantity" },
		{ "181", "Maximum production batch" },
		{ "182", "Cancelled quantity" },
		{ "183", "No delivery requirement in this instruction" },
		{ "184", "Quantity of material in ordered time" },
		{ "185", "Rejected quantity" },
		{ "186", "Cumulative quantity scheduled up to accumulation start date" },
		{ "187", "Quantity scheduled" },
		{ "188", "Number of identical handling units" },
		{ "189", "Number of packages in handling unit" },
		{ "190", "Despatch note quantity" },
		{ "191", "Adjustment to inventory quantity" },
		{ "192", "Free goods quantity" },
		{ "193", "Free quantity included" },
		{ "194", "Received and accepted" },
		{ "195", "Received, not accepted, to be returned" },
		{ "196", "Received, not accepted, to be destroyed" },
		{ "197", "Reordering level" },
		{ "198", "Quantity in transit" },
		{ "199", "Inventory withdrawal quantity" },
		{ "200", "Free quantity not included" },
		{ "201", "Recommended overhaul and repair quantity" },
		{ "202", "Quantity per next higher assembly" },
		{ "203", "Quantity per unit of issue" },
		{ "204", "Cumulative scrap quantity" },
		{ "205", "Publication turn size" },
		{ "206", "Recommended maintenance quantity" },
		{ "207", "Labour hours" },
		{ "208", "Quantity requirement for maintenance and repair of equipment" },
		{ "209", "Additional replenishment demand quantity" },
		{ "210", "Returned by consumer quantity" },
		{ "211", "Replenishment override quantity" },
		{ "212", "Quantity sold, net" },
		{ "213", "Transferred out quantity" },
		{ "214", "Transferred in quantity" },
		{ "215", "Unsaleable quantity" },
		{ "216", "Consumer reserved quantity" },
		{ "217", "Out of inventory quantity" },
		{ "218", "Quantity returned, defective or damaged" },
		{ "219", "Taxable quantity" },
	};
}