using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace indice.Edi.Tests.Issue256.Qualifiers;

/// <summary>
/// Reference qualifier
/// </summary>
public class ReferenceQualifier
{
	/// <summary>
	/// String assign converter
	/// </summary>
	public static implicit operator ReferenceQualifier(string s) => new ReferenceQualifier { Code = s };

	/// <summary>
	/// Code of the value
	/// </summary>
	public string? Code { get; set; }

	/// <summary>
	/// Value converted from code
	/// </summary>
	public string? Value => Code is null ? null : (Qualifiers.ContainsKey(Code) ? Qualifiers[Code] : null);

	/// <summary>
	/// All possible values
	/// </summary>
	[JsonIgnore]
	public Dictionary<string, string> Qualifiers => new Dictionary<string, string>
	{
		{ "AC", "Air cargo transfer manifest" },
		{ "AE", "Authorization for expense (AFE) number" },
		{ "AF", "Airlines flight identification number" },
		{ "AP", "Accounts receivable number" },
		{ "AU", "Authorization to meet competition No." },
		{ "AV", "Account payable number" },
		{ "BA", "Beginning meter reading actual" },
		{ "BC", "Buyer's contract number" },
		{ "BD", "Bid number" },
		{ "BE", "Beginning meter reading estimated" },
		{ "BH", "House bill of lading number" },
		{ "BM", "Bill of lading number" },
		{ "BN", "Booking reference number" },
		{ "BO", "Blanket order number" },
		{ "BR", "Broker or sales office number" },
		{ "BT", "Batch number/lot number" },
		{ "BW", "Blended with number" },
		{ "CD", "Credit note number" },
		{ "CG", "Consignee's order number" },
		{ "CH", "Customer catalogue number" },
		{ "CK", "Cheque number" },
		{ "CM", "Credit memo number" },
		{ "CN", "Carrier's reference number" },
		{ "CO", "Buyers order number" },
		{ "CP", "Condition of purchase document number" },
		{ "CR", "Customer reference number" },
		{ "CS", "Condition of sale document number" },
		{ "CT", "Contract number" },
		{ "CU", "Consignor's reference number" },
		{ "CV", "Container operators reference number" },
		{ "CW", "Package number" },
		{ "CZ", "Cooperation contract number" },
		{ "DA", "Deferment approval number" },
		{ "DB", "Buyer's debtor number" },
		{ "DI", "Distributor invoice number" },
		{ "DL", "Debit note number" },
		{ "DM", "Document number" },
		{ "DQ", "Delivery note number" },
		{ "DR", "Dock receipt number" },
		{ "EA", "Ending meter reading actual" },
		{ "EB", "Embargo permit number" },
		{ "ED", "Export declaration" },
		{ "EE", "Ending meter reading estimated" },
		{ "EI", "Employer's identification number" },
		{ "EN", "Embargo number" },
		{ "EP", "Export permit number" },
		{ "EQ", "Equipment number" },
		{ "ER", "Container/equipment receipt number" },
		{ "ET", "Excess transportation number" },
		{ "EX", "Export licence number" },
		{ "FC", "Fiscal number" },
		{ "FF", "Freight forwarder's reference number" },
		{ "FI", "File line identifier" },
		{ "FN", "Freight bill number" },
		{ "FO", "Foreign exchange" },
		{ "FS", "Final sequence number" },
		{ "FT", "Free zone identifier" },
		{ "FV", "File version number" },
		{ "FX", "Foreign exchange contract number" },
		{ "GA", "Standard's number" },
		{ "GC", "Government contract number" },
		{ "GD", "Standard's code number" },
		{ "GN", "Government reference number" },
		{ "HS", "Harmonised system number" },
		{ "IA", "Internal vendor number" },
		{ "IB", "In bond number" },
		{ "II", "Initial sample inspection report number" },
		{ "IL", "Internal order number" },
		{ "IP", "Import licence number" },
		{ "IS", "Invoice number suffix" },
		{ "IT", "Internal customer number" },
		{ "IV", "Invoice number" },
		{ "JB", "Job number" },
		{ "JE", "Ending job sequence number" },
		{ "LA", "Shipping label serial number" },
		{ "LB", "Lockbox" },
		{ "LC", "Letter of credit number" },
		{ "LI", "Line item reference number" },
		{ "LO", "Load planning number" },
		{ "LS", "Bar coded label serial number" },
		{ "MA", "Ship notice/manifest number" },
		{ "MB", "Master bill of lading number" },
		{ "MF", "Manufacturer's part number" },
		{ "MG", "Meter unit number" },
		{ "MH", "Manufacturing order number" },
		{ "MR", "Message recipient" },
		{ "MS", "Message sender" },
		{ "NA", "North American hazardous goods classification number" },
		{ "OH", "Current invoice number" },
		{ "OI", "Previous invoice number" },
		{ "ON", "Order number (purchase)" },
		{ "OP", "Original purchase order" },
		{ "OR", "General order number" },
		{ "PB", "Payer's financial institution account number" },
		{ "PC", "Production code" },
		{ "PD", "Promotion deal number" },
		{ "PE", "Plant number" },
		{ "PF", "Prime contractor contract number" },
		{ "PI", "Price list version number" },
		{ "PK", "Packing list number" },
		{ "PL", "Price list number" },
		{ "PP", "Purchase order change number" },
		{ "PQ", "Payment reference" },
		{ "PR", "Price quote number" },
		{ "PS", "Purchase order number suffix" },
		{ "PW", "Prior purchase order number" },
		{ "PY", "Payee's financial institution account number" },
		{ "RA", "Remittance advice number" },
		{ "RC", "Rail/road routing code" },
		{ "RE", "Release number" },
		{ "RF", "Export reference number" },
		{ "RR", "Payer's financial institution transit routing No.(ACH transfers)" },
		{ "RT", "Payee's financial institution transit routing No." },
		{ "SA", "Sales person number" },
		{ "SB", "Sales region number" },
		{ "SD", "Sales department number" },
		{ "SE", "Serial number" },
		{ "SF", "Ship from" },
		{ "SH", "Previous highest schedule number" },
		{ "SI", "SID (Shipper's identifying number for shipment)" },
		{ "SM", "Sales office number" },
		{ "SN", "Seal number" },
		{ "SP", "Scan line" },
		{ "SQ", "Container sequence number" },
		{ "SS", "Sellers reference number" },
		{ "SW", "Swap order number" },
		{ "SZ", "Specification number" },
		{ "TB", "Trucker's bill of lading" },
		{ "TE", "Telex message number" },
		{ "TF", "Transfer number" },
		{ "TI", "TIR carnet number" },
		{ "TL", "Tax exemption licence number" },
		{ "TN", "Transaction reference number" },
		{ "TP", "Test report number" },
		{ "UC", "Ultimate customer's reference number" },
		{ "UN", "United Nations dangerous goods (UNDG) number" },
		{ "UO", "Ultimate customer's order number" },
		{ "VA", "VAT registration number" },
		{ "VC", "Vendor contract number" },
		{ "VM", "Vessel identification" },
		{ "VN", "Order number (vendor)" },
		{ "VP", "Vendor product number" },
		{ "VR", "Vendor ID number" },
		{ "VS", "Vendor order number suffix" },
		{ "VT", "Motor vehicle identification number" },
		{ "VV", "Voucher number" },
		{ "WE", "Warehouse entry number" },
		{ "WM", "Weight agreement number" },
		{ "WN", "Well number" },
		{ "WR", "Warehouse receipt number" },
		{ "WS", "Warehouse storage location number" },
		{ "WY", "Rail waybill number" },
		{ "XA", "Company/place registration number" },
		{ "XC", "Cargo control number" },
		{ "XP", "Previous cargo control number" },
		{ "AAA", "Acknowledgement of order number" },
		{ "AAB", "Proforma invoice number" },
		{ "AAC", "Documentary credit number" },
		{ "AAD", "Contract addendum number" },
		{ "AAE", "Goods declaration number" },
		{ "AAG", "Offer number" },
		{ "AAJ", "Delivery order number" },
		{ "AAK", "Despatch advice number" },
		{ "AAL", "Drawing number" },
		{ "AAM", "Waybill number" },
		{ "AAN", "Delivery schedule number" },
		{ "AAO", "Consignee's shipment reference number" },
		{ "AAP", "Part consignment number" },
		{ "AAQ", "Unit load device (e.g. container) identification number" },
		{ "AAS", "Transport document number" },
		{ "AAT", "Master label number" },
		{ "AAU", "Despatch note number" },
		{ "AAV", "Enquiry number" },
		{ "AAY", "Carrier's agent reference number" },
		{ "AAZ", "Standard Carrier Alpha Code (SCAC) number" },
		{ "ABA", "Customs valuation decision number" },
		{ "ABB", "End use authorization number" },
		{ "ABC", "Anti-dumping case number" },
		{ "ABD", "Customs tariff number" },
		{ "ABE", "Declarant's reference number" },
		{ "ABG", "Customs decision request number" },
		{ "ABH", "Sub-house bill of lading number" },
		{ "ABI", "Deferred payment reference" },
		{ "ABJ", "Quota number" },
		{ "ABK", "Transit (onward carriage) guarantee (bond) number" },
		{ "ABL", "Customs guarantee number" },
		{ "ABO", "Originator's reference" },
		{ "ABP", "Declarant's Customs identity number" },
		{ "ABQ", "Importer reference number" },
		{ "ABR", "Export clearance instruction reference number" },
		{ "ABS", "Import clearance instruction reference number" },
		{ "ABT", "Customs declaration number" },
		{ "ABU", "Article number" },
		{ "ABW", "Stock keeping unit number" },
		{ "ABX", "Text Element Identifier deletion reference" },
		{ "ABY", "Allotment identification (Air)" },
		{ "ABZ", "Vehicle licence number" },
		{ "ACA", "Cargo acceptance order reference number" },
		{ "ACB", "US government agency number" },
		{ "ACC", "Shipping unit identification" },
		{ "ACD", "Additional reference number" },
		{ "ACE", "Related document number" },
		{ "ACF", "Addressee reference" },
		{ "ACG", "ATA carnet number" },
		{ "ACH", "Packaging unit identification" },
		{ "ACI", "Outerpackaging unit identification" },
		{ "ACJ", "Customer material specification number" },
		{ "ACK", "Bank reference" },
		{ "ACL", "Principal reference number" },
		{ "ACM", "Unique REINAC reference number of the sender" },
		{ "ACN", "Advice of collection number" },
		{ "ACO", "Iron charge number" },
		{ "ACP", "Hot roll number" },
		{ "ACQ", "Cold roll number" },
		{ "ACR", "Railway wagon number" },
		{ "ACS", "Unique CURRAC reference number of the sender" },
		{ "ACT", "Unique claims reference number of the sender" },
		{ "ACU", "Loss/event number" },
		{ "ACV", "Estimate order reference number" },
		{ "ACW", "Reference number to previous message" },
		{ "ACX", "Banker's acceptance" },
		{ "ACY", "Duty memo number" },
		{ "ACZ", "Equipment transport charge number" },
		{ "ADA", "Buyer's item number" },
		{ "ADB", "Matured certificate of deposit" },
		{ "ADC", "Loan" },
		{ "ADD", "Analysis number/test number" },
		{ "ADE", "Account number" },
		{ "ADF", "Treaty number" },
		{ "ADG", "Catastrophe number" },
		{ "ADH", "PCS Catastrophe" },
		{ "ADI", "Bureau signing (statement reference)" },
		{ "ADJ", "Company / syndicate reference 1" },
		{ "ADK", "Company / syndicate reference 2" },
		{ "ADL", "Ordering customer consignment reference number" },
		{ "ADM", "Shipowner's authorization number" },
		{ "ADN", "Inland transport order number" },
		{ "ADO", "Container work order reference number" },
		{ "ADP", "Statement number" },
		{ "ADQ", "Unique market reference" },
		{ "ADR", "Bureau signing (original FDO reference)" },
		{ "ADS", "Original FDO transaction reference" },
		{ "ADT", "Group accounting" },
		{ "ADU", "Broker reference 1" },
		{ "ADV", "Broker reference 2" },
		{ "ADW", "Lloyd's claims office reference" },
		{ "ADY", "Report number" },
		{ "ADZ", "Trader account number" },
		{ "AEA", "Government agency reference number" },
		{ "AEB", "Assembly number" },
		{ "AEC", "Symbol number" },
		{ "AED", "Commodity number" },
		{ "AEE", "Eur 1 certificate number" },
		{ "AEF", "Customer process specification number" },
		{ "AEG", "Customer specification number" },
		{ "AEH", "Applicable instructions or standards" },
		{ "AEI", "Registration number of previous Customs declaration" },
		{ "AEJ", "Post-entry reference" },
		{ "AEK", "Payment order number" },
		{ "AEL", "Delivery number (transport)" },
		{ "AEM", "Transport route" },
		{ "AEN", "Customer's unit inventory number" },
		{ "AEO", "Product reservation number" },
		{ "AEP", "Project number" },
		{ "AEQ", "Drawing list number" },
		{ "AER", "Project specification number" },
		{ "AES", "Primary reference" },
		{ "AET", "Request for cancellation number" },
		{ "AEU", "Supplier's control number" },
		{ "AEV", "Shipping note number" },
		{ "AEW", "Empty container bill number" },
		{ "AEX", "Non-negotiable maritime transport document number" },
		{ "AEY", "Substitute air waybill number" },
		{ "AEZ", "Despatch note (post parcels) number" },
		{ "AFA", "Through bill of lading number" },
		{ "AFB", "Cargo manifest number" },
		{ "AFC", "Bordereau number" },
		{ "AFD", "Customs item number" },
		{ "AFE", "Export Control Commodity number (ECCN)" },
		{ "AFF", "Marking/label reference" },
		{ "AFG", "Tariff number" },
		{ "AFH", "Replenishment purchase order number" },
		{ "AFI", "Immediate transportation no. for in bond movement" },
		{ "AFJ", "Transportation exportation no. for in bond movement" },
		{ "AFK", "Immediate exportation no. for in bond movement" },
		{ "AFL", "Associated invoices" },
		{ "AFM", "Secondary Customs reference" },
		{ "AFN", "Account party's reference" },
		{ "AFO", "Beneficiary's reference" },
		{ "AFP", "Second beneficiary's reference" },
		{ "AFQ", "Applicant's bank reference" },
		{ "AFR", "Issuing bank's reference" },
		{ "AFS", "Beneficiary's bank reference" },
		{ "AFT", "Direct payment valuation number" },
		{ "AFU", "Direct payment valuation request number" },
		{ "AFV", "Quantity valuation number" },
		{ "AFW", "Quantity valuation request number" },
		{ "AFX", "Bill of quantities number" },
		{ "AFY", "Payment valuation number" },
		{ "AFZ", "Situation number" },
		{ "AGA", "Agreement to pay number" },
		{ "AGB", "Contract party reference number" },
		{ "AGC", "Account party's bank reference" },
		{ "AGD", "Agent's bank reference" },
		{ "AGE", "Agent's reference" },
		{ "AGF", "Applicant's reference" },
		{ "AGG", "Dispute number" },
		{ "AGH", "Credit rating agency's reference number" },
		{ "AGI", "Request number" },
		{ "AGJ", "Single transaction sequence number" },
		{ "AGK", "Application reference number" },
		{ "AGL", "Delivery verification certificate" },
		{ "AGM", "Number of temporary importation document" },
		{ "AGN", "Reference number quoted on statement" },
		{ "AGO", "Sender's reference to the original message" },
		{ "AGP", "Company issued equipment ID" },
		{ "AGQ", "Domestic flight number" },
		{ "AGR", "International flight number" },
		{ "AGS", "Employer identification number of service bureau" },
		{ "AGT", "Service group identification number" },
		{ "AGU", "Member number" },
		{ "AGV", "Previous member number" },
		{ "AGW", "Scheme/plan number" },
		{ "AGX", "Previous scheme/plan number" },
		{ "AGY", "Receiving party's member identification" },
		{ "AGZ", "Payroll number" },
		{ "AHA", "Packaging specification number" },
		{ "AHB", "Authority issued equipment identification" },
		{ "AHC", "Training flight number" },
		{ "AHD", "Fund code number" },
		{ "AHE", "Signal code number" },
		{ "AHF", "Major force program number" },
		{ "AHG", "Nomination number" },
		{ "AHH", "Laboratory registration number" },
		{ "AHI", "Transport contract reference number" },
		{ "AHJ", "Payee's reference number" },
		{ "AHK", "Payer's reference number" },
		{ "AHL", "Creditor's reference number" },
		{ "AHM", "Debtor's reference number" },
		{ "AHN", "Joint venture reference number" },
		{ "AHO", "Chamber of Commerce registration number" },
		{ "AHP", "Tax registration number" },
		{ "AHQ", "Wool identification number" },
		{ "AHR", "Wool tax reference number" },
		{ "AHS", "Meat processing establishment registration number" },
		{ "AHT", "Quarantine/treatment status reference number" },
		{ "AHU", "Request for quote number" },
		{ "AHV", "Manual processing authority number" },
		{ "AHW", "Import permit number" },
		{ "AHX", "Rate note number" },
		{ "AHY", "Freight Forwarder number" },
		{ "AHZ", "Customs release code" },
		{ "AIA", "Compliance code number" },
		{ "AIB", "Department of transportation bond number" },
		{ "AIC", "Export establishment number" },
		{ "AID", "Certificate of conformity" },
		{ "AIE", "Ministerial certificate of homologation" },
		{ "AIF", "Previous delivery instruction number" },
		{ "AIG", "Passport number" },
		{ "AIH", "Common transaction reference number" },
		{ "AII", "Bank's common transaction reference number" },
		{ "AIJ", "Customer's individual transaction reference number" },
		{ "AIK", "Bank's individual transaction reference number" },
		{ "AIL", "Customer's common transaction reference number" },
		{ "AIM", "Individual transaction reference number" },
		{ "AIN", "Product sourcing agreement number" },
		{ "AIO", "Customs transhipment number" },
		{ "AIP", "Customs preference inquiry number" },
		{ "AIQ", "Packing plant number" },
		{ "AIR", "Original certificate number" },
		{ "AIS", "Processing plant number" },
		{ "AIT", "Slaughter plant number" },
		{ "AIU", "Charge card account number" },
		{ "AIV", "Event reference number" },
		{ "AIW", "Transport section reference number" },
		{ "AIX", "Referred product for mechanical analysis" },
		{ "AIY", "Referred product for chemical analysis" },
		{ "AIZ", "Consolidated invoice number" },
		{ "AJA", "Part reference indicator in a drawing" },
		{ "AJB", "U.S. Code of Federal Regulations (CFR)" },
		{ "AJC", "Purchasing activity clause number" },
		{ "AJD", "U.S. Defense Federal Acquisition Regulation Supplement" },
		{ "AJE", "Agency clause number" },
		{ "AJF", "Circular publication number" },
		{ "AJG", "U.S. Federal Acquisition Regulation" },
		{ "AJH", "U.S. General Services Administration Regulation" },
		{ "AJI", "U.S. Federal Information Resources Management Regulation" },
		{ "AJJ", "Paragraph" },
		{ "AJK", "Special instructions number" },
		{ "AJL", "Site specific procedures, terms, and conditions number" },
		{ "AJM", "Master solicitation procedures, terms, and conditions number" },
		{ "AJN", "U.S. Department of Veterans Affairs Acquisition Regulation" },
		{ "AJO", "Military Interdepartmental Purchase Request (MIPR) number" },
		{ "AJP", "Foreign military sales number" },
		{ "AJQ", "Defense priorities allocation system priority rating" },
		{ "AJR", "Wage determination number" },
		{ "AJS", "Agreement number" },
		{ "AJT", "Standard Industry Classification (SIC) number" },
		{ "AJU", "End item number" },
		{ "AJV", "Federal supply schedule item number" },
		{ "AJW", "Technical document number" },
		{ "AJX", "Technical order number" },
		{ "AJY", "Suffix" },
		{ "AJZ", "Transportation account number" },
		{ "AKA", "Container disposition order reference number" },
		{ "AKB", "Container prefix" },
		{ "AKC", "Transport equipment return reference" },
		{ "AKD", "Transport equipment survey reference" },
		{ "AKE", "Transport equipment survey report number" },
		{ "AKF", "Transport equipment stuffing order" },
		{ "AKG", "Vehicle Identification Number (VIN)" },
		{ "AKK", "Meter reading at the beginning of the delivery." },
		{ "AKL", "Meter reading at the end of delivery" },
		{ "AKM", "Replenishment purchase order range start number" },
		{ "AKO", "Action authorization number" },
		{ "AKP", "Appropriation number" },
		{ "AKQ", "Product change authority number" },
		{ "AKR", "General cargo consignment reference number" },
		{ "AKS", "Catalogue sequence number" },
		{ "AKT", "Forwarding order number" },
		{ "AKU", "Transport equipment survey reference number" },
		{ "AKV", "Lease contract reference" },
		{ "AKW", "Transport costs reference number" },
		{ "AKX", "Transport equipment stripping order" },
		{ "ALA", "Procurement budget number" },
		{ "ALB", "Domestic inventory management code" },
		{ "ALC", "Customer reference number assigned to previous balance of payment information" },
		{ "ALD", "Previous credit advice reference number" },
		{ "ALE", "Reporting form number" },
		{ "ALF", "Authorization number for exception to dangerous goods regulations" },
		{ "ALG", "Dangerous goods security number" },
		{ "ALH", "Dangerous goods transport licence number" },
		{ "ALI", "Previous rental agreement number" },
		{ "ALJ", "Next rental agreement reason number" },
		{ "ALK", "Consignee's invoice number" },
		{ "ALL", "Message batch number" },
		{ "ALM", "Previous delivery schedule number" },
		{ "ALN", "Physical inventory recount reference number" },
		{ "ALO", "Receiving advice number" },
		{ "ALP", "Returnable container reference number" },
		{ "ALQ", "Returns notice number" },
		{ "ALR", "Sales forecast number" },
		{ "ALS", "Sales report number" },
		{ "ALT", "Previous tax control number" },
		{ "ALU", "AGERD (Aerospace Ground Equipment Requirement Data) number" },
		{ "ALV", "Registered capital reference" },
		{ "ALW", "Standard number of inspection document" },
		{ "ALX", "Model" },
		{ "ALY", "Financial management reference" },
		{ "ALZ", "NOTIfication for COLlection number (NOTICOL)" },
		{ "AMA", "Previous request for metered reading reference number" },
		{ "AMB", "Next rental agreement number" },
		{ "AMC", "Reference number of a request for metered reading" },
		{ "AMD", "Hastening number" },
		{ "AME", "Repair data request number" },
		{ "AMF", "Consumption data request number" },
		{ "AMG", "Profile number" },
		{ "AMI", "Government quality assurance and control level Number" },
		{ "AMJ", "Payment plan reference" },
		{ "AMK", "Procurement budget number" },
		{ "AML", "Replenishment purchase order range end number" },
		{ "AMN", "Canadian excise entry number" },
		{ "AMQ", "US, Department of Transportation bond surety code" },
		{ "AMR", "US, Food and Drug Administration establishment indicator" },
		{ "AMS", "US, Federal Communications Commission (FCC) import condition number" },
		{ "AMT", "Goods and Services Tax identification number" },
		{ "AMU", "Integrated logistic support cross reference number" },
		{ "ASC", "Assuming company" },
		{ "AWB", "Air waybill number" },
		{ "CAS", "IATA Cargo Agent CASS Address number" },
		{ "CEC", "Ceding company" },
		{ "CFE", "Consignee's further order" },
		{ "CFO", "Consignor's further order" },
		{ "CKN", "Checking number" },
		{ "CMR", "Road consignment note number" },
		{ "CNO", "Charge note reference number" },
		{ "COF", "Call off order number" },
		{ "CRN", "Conveyance reference number" },
		{ "CST", "Team assignment number" },
		{ "DAN", "Debit account number" },
		{ "ERN", "Exporter's reference number" },
		{ "FLW", "Flow reference number" },
		{ "GDN", "General declaration number" },
		{ "HWB", "House waybill number" },
		{ "ICA", "IATA cargo agent code number" },
		{ "ICE", "Insurance certificate reference number" },
		{ "ICO", "Insurance contract reference number" },
		{ "INB", "Intermediary broker" },
		{ "INN", "Interchange number new" },
		{ "INO", "Interchange number old" },
		{ "LAN", "Loading authorization number" },
		{ "LAR", "Lower article number of range" },
		{ "MRN", "Mailing reference number" },
		{ "MSS", "Manufacturer's material safety data sheet number" },
		{ "MWB", "Master air waybill number" },
		{ "POR", "Purchase order response number" },
		{ "RCN", "Railway consignment note number" },
		{ "REN", "Received number" },
		{ "SRN", "Shipment reference number" },
		{ "STA", "Station reference number" },
		{ "UAR", "Upper serial number of range" },
		{ "UCN", "Unique consignment reference number" },
		{ "VON", "Voyage number" },
		{ "ZZZ", "Mutually defined reference number" },
	};
}