using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace indice.Edi.Tests.Issue256.Qualifiers;

/// <summary>
/// Special services, coded
/// </summary>
public class SpecialServicesCoded
{
	/// <summary>
	/// String assign converter
	/// </summary>
	public static implicit operator SpecialServicesCoded(string s) => new SpecialServicesCoded { Code = s };

	/// <summary>
	/// Code of the value
	/// </summary>
	public string? Code { get; set; }

	/// <summary>
	/// Value converted from code
	/// </summary>
	public string? Value => Code is null ? null : (Qualifiers.ContainsKey(Code) ? Qualifiers[Code] : null);

	/// <summary>
	/// All possible values
	/// </summary>
	[JsonIgnore]
	public Dictionary<string, string> Qualifiers => new Dictionary<string, string>
	{
		{ "AA", "Advertising allowance" },
		{ "AG", "Silver surcharge" },
		{ "AJ", "Adjustments" },
		{ "AL", "Aluminium surcharge" },
		{ "AM", "Additional material" },
		{ "AU", "Authentication charge" },
		{ "CA", "Cataloguing services" },
		{ "CB", "Commission" },
		{ "CD", "Car loading" },
		{ "CG", "Cleaning charge" },
		{ "CK", "COD charge" },
		{ "CL", "Contract allowance" },
		{ "CO", "Cents off" },
		{ "CP", "Competitive price" },
		{ "CS", "Cigarette stamping" },
		{ "CT", "Count and recount" },
		{ "CW", "Container allowance" },
		{ "DA", "Defective allowance" },
		{ "DI", "Discount" },
		{ "DL", "Delivery" },
		{ "DM", "Demurrage" },
		{ "EG", "Engraving" },
		{ "EP", "Expediting premium" },
		{ "ER", "Exchange rate guarantee charge" },
		{ "EX", "Export shipping charge" },
		{ "FA", "Freight allowance" },
		{ "FC", "Freight charge" },
		{ "FG", "Free goods" },
		{ "FH", "Filling/handling charge" },
		{ "FI", "Finance charge" },
		{ "FN", "Special finish charge" },
		{ "FR", "Flat rate" },
		{ "HD", "Handling" },
		{ "HH", "Hoisting and hauling" },
		{ "IA", "Invoice adjustment" },
		{ "ID", "Inside delivery charge" },
		{ "IF", "Inspection fee" },
		{ "IN", "Insurance" },
		{ "IR", "Installation and training" },
		{ "IS", "Invoice services" },
		{ "KO", "Koshering" },
		{ "L1", "Shipper load, carrier count" },
		{ "LA", "Labelling" },
		{ "LF", "Legalisation fee" },
		{ "LS", "Local sales tax" },
		{ "MA", "Material allowance (special materials)" },
		{ "MC", "Material surcharge (special materials)" },
		{ "MI", "Mail invoice" },
		{ "ML", "Mail invoice to each location" },
		{ "OA", "Outside cable connectors" },
		{ "PA", "Pack invoice with shipment" },
		{ "PC", "Packing" },
		{ "PD", "Palladium surcharge" },
		{ "PI", "Pick-up allowance" },
		{ "PL", "Palletizing" },
		{ "PN", "Pallet charge" },
		{ "PO", "Per order charge" },
		{ "QD", "Quantity discount" },
		{ "RE", "Re-delivery charge" },
		{ "RF", "Refurbishing charge" },
		{ "RH", "Rail wagon hire" },
		{ "RO", "Roe allowance/charge" },
		{ "RP", "Repair charge" },
		{ "RV", "Freight charge/costs of loading" },
		{ "SA", "Salvage" },
		{ "SC", "Surcharge" },
		{ "SD", "Shrinkage allowance" },
		{ "SF", "Special rebate" },
		{ "SG", "Shrink-wrap charge" },
		{ "SH", "Special handling service" },
		{ "SM", "Special finish" },
		{ "ST", "Stamp duties" },
		{ "SU", "Set-up" },
		{ "SZ", "Steel surcharge" },
		{ "TD", "Trade discount" },
		{ "TS", "State tax" },
		{ "TT", "Transportation - third party billing" },
		{ "TV", "Transportation - vendor provided" },
		{ "TX", "Tax" },
		{ "TZ", "Temporary allowance" },
		{ "UM", "Unsaleable merchandise allowance" },
		{ "V1", "Drop yard" },
		{ "V2", "Drop dock" },
		{ "VL", "Vehicle load allowance" },
		{ "WH", "Warehousing" },
		{ "YY", "Split pickup" },
		{ "AAA", "Telecommunication charges" },
		{ "AAB", "Returned goods charges" },
		{ "AAC", "Modification costs" },
		{ "AAD", "Job-order production" },
		{ "AAE", "Outlays" },
		{ "AAF", "Off-premises surcharge" },
		{ "AAG", "Gold surcharge" },
		{ "AAH", "Processing surcharge" },
		{ "AAI", "Attestation fee" },
		{ "AAJ", "Copper surcharge" },
		{ "AAK", "Energy surcharge" },
		{ "AAL", "Deduction for missing parts" },
		{ "AAM", "Rubber surcharge" },
		{ "AAN", "Brass surcharge" },
		{ "AAO", "Material surcharge/deduction" },
		{ "AAP", "Lead surcharge" },
		{ "AAQ", "Price index surcharge" },
		{ "AAR", "Platinum surcharge" },
		{ "AAS", "Acceptance cost" },
		{ "AAT", "Rush delivery" },
		{ "AAU", "Selenium surcharge" },
		{ "AAV", "Special construction charge" },
		{ "AAW", "Deduction for delayed return" },
		{ "AAX", "Wolfram surcharge" },
		{ "AAY", "Airport fee" },
		{ "AAZ", "Concession fee" },
		{ "ABA", "Compulsory storage fee" },
		{ "ABB", "Defuel" },
		{ "ABC", "Into plane fee" },
		{ "ABD", "Overtime" },
		{ "ABE", "Reservicing charge" },
		{ "ABF", "Tooling cost" },
		{ "ABG", "Tooling charge" },
		{ "ABH", "Throughput allowance" },
		{ "ABI", "Superfund fee" },
		{ "ABJ", "Airport system fee" },
		{ "ABK", "Miscellaneous" },
		{ "ABL", "Packaging surcharge" },
		{ "ABM", "Scrap surcharge" },
		{ "ABN", "Dunnage charge" },
		{ "ABO", "Air freight transportation" },
		{ "ABP", "Carriage charge" },
		{ "ABQ", "Tonnage rebate" },
		{ "ABR", "Containerisation" },
		{ "ABS", "Carton packing" },
		{ "ABT", "Hessian wrapped" },
		{ "ABU", "Polyethylene wrap packing" },
		{ "ABV", "Miscellaneous customs charge" },
		{ "ABW", "Customs duty charge" },
		{ "ABX", "Miscellaneous special tooling charge" },
		{ "ABY", "Tooling amortisation" },
		{ "ABZ", "Miscellaneous rebate or discount" },
		{ "ACA", "Allowance" },
		{ "ACB", "Future discount off retail" },
		{ "ACC", "Miscellaneous setting costs (tooling)" },
		{ "ACD", "Minimum amount costs for quantity based surcharges" },
		{ "ACE", "Below schedule quantity after quantity-based surcharge" },
		{ "ACF", "Miscellaneous treatment" },
		{ "ACG", "Enamelling treatment" },
		{ "ACH", "Heat treatment" },
		{ "ACI", "Plating treatment" },
		{ "ACJ", "Painting" },
		{ "ACK", "Polishing" },
		{ "ACL", "Priming" },
		{ "ACM", "Preservation treatment" },
		{ "ACN", "Miscellaneous other surcharges" },
		{ "ACO", "Alloy surcharge" },
		{ "ACP", "Coke surcharge" },
		{ "ACQ", "Royalty surcharge" },
		{ "ACR", "Wheel handling charge" },
		{ "ACS", "Fitting surcharge" },
		{ "ACT", "Non-standard surcharge" },
		{ "ACU", "Standard surcharge" },
		{ "ACV", "Wheel surcharge" },
		{ "ACW", "Washer surcharge" },
		{ "ACX", "Ocean freight charge" },
		{ "ACY", "Container deposit charge" },
		{ "ACZ", "Damaged merchandise" },
		{ "ADA", "Bopsheet charge" },
		{ "ADB", "Drum deposit" },
		{ "ADC", "Consolidation" },
		{ "ADD", "Inland transportation" },
		{ "ADE", "Bill of lading charge" },
		{ "ADF", "Excise tax-destination" },
		{ "ADG", "Customs bond charge" },
		{ "ADH", "Per pound charge" },
		{ "ADI", "Royalties" },
		{ "ADJ", "Airbag charge" },
		{ "ADK", "Transfer charge" },
		{ "ADL", "Slipsheet charge" },
		{ "ADM", "Binding services" },
		{ "ADN", "Repair or replacement of broken returnable package" },
		{ "ADO", "Efficient logistics" },
		{ "ADP", "Merchandising" },
		{ "ADQ", "Product mix" },
		{ "ADR", "Other services" },
		{ "ADS", "Full pallet ordering" },
		{ "ADT", "Pick-up" },
		{ "ADU", "Handling by the 1st level sub-contractor" },
		{ "ADV", "Handling by the 2nd level sub-contractor" },
		{ "ADX", "Handling by the contractor" },
		{ "ADY", "New product introduction" },
		{ "AEA", "Diversion" },
		{ "AEB", "Disconnect" },
		{ "AEC", "Distribution" },
		{ "AED", "Handling of hazardous cargo" },
		{ "AEF", "Rents and leases" },
		{ "AEG", "System usage" },
		{ "AEH", "Location differential" },
		{ "CAA", "Cancellation charge" },
		{ "CAB", "Cartage" },
		{ "CAC", "Cash discount" },
		{ "CAD", "Certification fee" },
		{ "CAE", "Certificate of conformance" },
		{ "CAF", "Certificate of origin" },
		{ "CAG", "Competitive allowance" },
		{ "CAH", "Competitive auto allowance" },
		{ "CAI", "Cutting charge" },
		{ "CAJ", "Consular costs" },
		{ "CAK", "Customer collection rebate" },
		{ "DAA", "Deficit freight" },
		{ "DAB", "Layout/design" },
		{ "DAD", "Driver assigned unloading" },
		{ "DAE", "Distributor discount/allowance" },
		{ "EAA", "Early buy allowance" },
		{ "EAB", "Early payment allowance" },
		{ "FAA", "Fabrication charge" },
		{ "FAB", "Freight equalization" },
		{ "FAC", "Freight surcharge" },
		{ "GAA", "Grinding" },
		{ "HAA", "Hose charge" },
		{ "IAA", "Installation" },
		{ "IAB", "Installation and warranty" },
		{ "LAA", "Labour charge" },
		{ "LAB", "Labor (repair and return orders)" },
		{ "LAC", "License fee" },
		{ "MAA", "Mileage or travel" },
		{ "MAB", "Mileage fee (for repair and return)" },
		{ "MAC", "Minimum order/minimum billing charge" },
		{ "MAD", "Monthly rental" },
		{ "MAE", "Mounting" },
		{ "NAA", "Non-returnable containers" },
		{ "OAA", "Overtime loading" },
		{ "PAA", "Phosphatizing (steel treatment)" },
		{ "PAB", "Postage charge" },
		{ "PAC", "Premium charge" },
		{ "PAD", "Promotional allowance" },
		{ "PAE", "Promotional discount" },
		{ "QAA", "Quantity surcharge" },
		{ "RAA", "Rebate" },
		{ "RAB", "Repack charge" },
		{ "RAC", "Repair" },
		{ "RAD", "Returnable container" },
		{ "RAE", "Resellers discount" },
		{ "RAF", "Restocking charge" },
		{ "RAG", "Roll rebate" },
		{ "RAH", "Road/rail tanker rebate" },
		{ "SAA", "Shipping and handling" },
		{ "SAB", "Special allowance" },
		{ "SAC", "Special credit" },
		{ "SAD", "Special packaging" },
		{ "SAE", "Stamping" },
		{ "SAF", "Supplemental items" },
		{ "SAG", "Surcharge (dollar value)" },
		{ "SAH", "Surcharge (percentage)" },
		{ "SAI", "Shipper load, consignee unload" },
		{ "SAJ", "Small packages charge" },
		{ "TAA", "Telephone charge" },
		{ "TAB", "Tank rental" },
		{ "TAC", "Testing charge" },
		{ "TAD", "Testing allowance" },
		{ "TAE", "Truckload discount" },
		{ "VAA", "Vendor freight" },
		{ "VAB", "Volume discount" },
		{ "XAA", "Combine all same day shipment" },
		{ "ZZZ", "Mutually defined" },
	};
}